// <auto-generated>
//   This file is generated by the a2n.Vista TypeScript client generator. Do not edit by hand.
//   It declares the fixed Vista envelopes, ProblemDetails, the per-view row/write DTOs, and the
//   single generic ViewListResult<TRow>/PagedResult<TRow> result types. Each type is declared
//   exactly once and referenced by name; the FilterNode family lives in ./filter-node.
// </auto-generated>

import type { FilterNode } from "./filter-node";

export interface CustomerRow {
  companyName: string;
  contactName?: string | null;
  country?: string | null;
  customerId: string;
  isActive: boolean;
}

export interface PagedResult<TRow> {
  items: TRow[];
  pageIndex: number;
  pageSize: number;
  totalPages: number;
  totalRows: number;
}

export interface ProblemDetails {
  code?: string | null;
  detail?: string | null;
  instance?: string | null;
  status?: number | null;
  title?: string | null;
  type?: string | null;
}

export interface ViewListResult<TRow> {
  page: PagedResult<TRow>;
  totalRowsUnfiltered: number;
}

export interface VistaDetailRequestBody {
  key: unknown;
}

export interface VistaFieldMetadataResponse {
  allowedOperators: string;
  clrType: string;
  isFilterable: boolean;
  isHidden: boolean;
  isPrimaryKey: boolean;
  isScopable: boolean;
  isSearchable: boolean;
  isSortable: boolean;
  label: string;
  name: string;
}

export interface VistaListRequestBody {
  filter?: FilterNode;
  format?: string | null;
  page?: number;
  pageSize?: number;
  scope?: FilterNode;
  search?: string | null;
  sort?: VistaSortBody[] | null;
}

export interface VistaMetadataResponse {
  fields: VistaFieldMetadataResponse[];
  isReadOnly: boolean;
  keyFields: string[];
  maxExportRows: number;
  maxPageSize: number;
  name: string;
  route: string;
}

export interface VistaSortBody {
  desc?: boolean;
  field?: string;
}
