// <auto-generated>
//   This file is generated by the a2n.Vista TypeScript client generator. Do not edit by hand.
//   It defines the typed client for the Customers view.
// </auto-generated>

import { classifyResponse, transportError } from "../runtime/result";
import type { ClassifiableResponse, ClientResult } from "../runtime/result";
import type { ClientContext } from "../runtime/client-context";
import type { HttpRequest, HttpResponse } from "../runtime/http-transport";
import type { RawPayload } from "../runtime/raw-payload";
import type { CustomerRow, ViewListResult, VistaDetailRequestBody, VistaListRequestBody, VistaMetadataResponse } from "../types";

/**
 * The typed client for the Customers view's facets. Construct it with a shared
 * {@link ClientContext}; each method routes its request through the context's transport and
 * returns a typed {@link ClientResult} without throwing.
 */
export class CustomersClient {
  constructor(private readonly ctx: ClientContext) {}

  /**
   * Calls the detail facet (POST /api/views/customers/detail).
   */
  detail(body: VistaDetailRequestBody): Promise<ClientResult<CustomerRow>> {
    return this.send<CustomerRow>(
      "detail",
      "POST",
      "/api/views/customers/detail",
      JSON.stringify(body),
      (raw) => JSON.parse(raw) as CustomerRow,
    );
  }

  /**
   * Calls the export facet (POST /api/views/customers/export).
   */
  export(body: VistaListRequestBody): Promise<ClientResult<RawPayload>> {
    return this.send<RawPayload>(
      "export",
      "POST",
      "/api/views/customers/export",
      JSON.stringify(body),
      (raw) => raw,
    );
  }

  /**
   * Calls the list facet (POST /api/views/customers/list).
   */
  list(body: VistaListRequestBody): Promise<ClientResult<ViewListResult<CustomerRow>>> {
    return this.send<ViewListResult<CustomerRow>>(
      "list",
      "POST",
      "/api/views/customers/list",
      JSON.stringify(body),
      (raw) => JSON.parse(raw) as ViewListResult<CustomerRow>,
    );
  }

  /**
   * Calls the metadata facet (GET /api/views/customers/metadata).
   */
  metadata(): Promise<ClientResult<VistaMetadataResponse>> {
    return this.send<VistaMetadataResponse>(
      "metadata",
      "GET",
      "/api/views/customers/metadata",
      undefined,
      (raw) => JSON.parse(raw) as VistaMetadataResponse,
    );
  }

  /**
   * Builds and routes a single request through the shared context and classifies the response
   * into a typed {@link ClientResult} without throwing. A rejecting transport becomes a
   * `transport-error` result with no retry (Requirement 6.6).
   */
  private async send<T>(
    facet: string,
    method: string,
    path: string,
    body: string | undefined,
    parseSuccess: (raw: string) => T,
  ): Promise<ClientResult<T>> {
    const headers: Record<string, string> = {};
    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
    }

    const request: HttpRequest = {
      method,
      url: this.ctx.resolveUrl(path),
      headers,
      ...(body === undefined ? {} : { body }),
    };

    let response: HttpResponse;
    try {
      response = await this.ctx.transport.send(request);
    } catch (error) {
      return transportError<T>(error);
    }

    const classifiable: ClassifiableResponse = {
      status: response.status,
      contentType: readContentType(response.headers),
      body: response.body,
    };
    return classifyResponse(classifiable, parseSuccess);
  }
}

/**
 * Resolves the `Content-Type` response header case-insensitively (a custom transport may not
 * lower-case header names the way the default `fetch` transport does), returning `null` when it
 * is absent.
 */
function readContentType(headers: Readonly<Record<string, string>>): string | null {
  for (const [name, value] of Object.entries(headers)) {
    if (name.toLowerCase() === "content-type") {
      return value;
    }
  }
  return null;
}
