// <auto-generated>
//   This file is generated by the a2n.Vista TypeScript client generator. Do not edit by hand.
//   It defines the raw, unparsed payload type an `export` operation preserves its response body as.
// </auto-generated>

/**
 * The raw, unparsed body of an `export` response (Requirement 4.7). The `export` operation returns the
 * response body verbatim as text rather than deserializing it into a typed object, so a consumer can decode
 * it however the chosen export format requires (for example, CSV or a spreadsheet's bytes as a data URL).
 */
export type RawPayload = string;
