// <auto-generated>
//   This file is generated by the a2n.Vista TypeScript client generator.
//   Do not edit by hand; regenerate it from the OpenAPI document instead.
// </auto-generated>
//
// Base-URL join and validation helpers for the generated client. These functions are
// framework-agnostic and rely only on the global `URL` constructor for parsing and validation.

/**
 * The outcome of validating a base URL supplied at client construction, discriminated on `kind`:
 * - `ok`    the URL is a valid absolute HTTPS URL; construction may proceed.
 * - `warn`  the URL is a valid non-HTTPS loopback URL; construction may proceed, but a warning applies.
 * - `error` the URL is absent, empty, syntactically invalid, or a non-HTTPS non-loopback URL;
 *           construction must fail and no request may be issued.
 */
export type BaseUrlValidation =
  | { readonly kind: "ok"; readonly url: string }
  | { readonly kind: "warn"; readonly url: string; readonly warning: string }
  | { readonly kind: "error"; readonly error: string };

/**
 * The loopback hosts permitted to use a non-HTTPS scheme. A non-HTTPS base URL is accepted with a
 * warning only when its host is one of these; every other non-HTTPS host is rejected.
 */
const loopbackHosts: ReadonlySet<string> = new Set<string>(["localhost", "127.0.0.1", "::1"]);

/**
 * Joins a base URL and an operation path using exactly one `/` separator. Any trailing `/` on the base
 * and any leading `/` on the path are collapsed at the join, while the path's own internal segments are
 * preserved. An empty path (after trimming leading slashes) yields the base URL unchanged.
 */
export function joinUrl(baseUrl: string, path: string): string {
  const base = baseUrl.replace(/\/+$/, "");
  const suffix = path.replace(/^\/+/, "");
  return suffix.length === 0 ? base : `${base}/${suffix}`;
}

/**
 * Removes a single pair of surrounding brackets from an IPv6 host (e.g. `[::1]` -> `::1`) so it can be
 * compared against the loopback host set; other hosts are returned unchanged.
 */
function normalizeHost(hostname: string): string {
  return hostname.startsWith("[") && hostname.endsWith("]") ? hostname.slice(1, -1) : hostname;
}

/**
 * Validates a base URL for client construction and classifies the outcome:
 * - absent, empty, or not a syntactically valid absolute URL -> `error` (construction fails).
 * - non-HTTPS scheme over a loopback host -> `warn` (construction may proceed with a warning).
 * - non-HTTPS scheme over a non-loopback host -> `error` (construction fails).
 * - HTTPS -> `ok`.
 */
export function validateBaseUrl(baseUrl: string): BaseUrlValidation {
  if (typeof baseUrl !== "string" || baseUrl.trim().length === 0) {
    return { kind: "error", error: "The base URL is absent or empty." };
  }

  let parsed: URL;
  try {
    parsed = new URL(baseUrl);
  } catch {
    return {
      kind: "error",
      error: `The base URL "${baseUrl}" is not a syntactically valid absolute URL.`,
    };
  }

  if (parsed.protocol === "https:") {
    return { kind: "ok", url: baseUrl };
  }

  const scheme = parsed.protocol.replace(/:$/, "");
  if (loopbackHosts.has(normalizeHost(parsed.hostname).toLowerCase())) {
    return {
      kind: "warn",
      url: baseUrl,
      warning: `The base URL "${baseUrl}" uses the non-HTTPS scheme "${scheme}" over a loopback host; traffic will not be encrypted in transit.`,
    };
  }

  return {
    kind: "error",
    error: `The base URL "${baseUrl}" uses the non-HTTPS scheme "${scheme}" over a non-loopback host; use HTTPS for non-loopback hosts.`,
  };
}
