namespace a2n.Vista.Client.TypeScript.Emit.Runtime;

/// <summary>
/// Emits the framework-agnostic HTTP transport runtime file (<c>runtime/http-transport.ts</c>): the
/// <c>HttpRequest</c>/<c>HttpResponse</c>/<c>HttpTransport</c> contracts (design §B.1) and the default
/// <c>fetch</c>-backed transport. The generated client routes every request through the injected
/// <c>HttpTransport</c> and performs no direct network I/O otherwise (Requirement 6.1); when no transport is
/// supplied it falls back to the platform global <c>fetch</c> (Requirement 6.2); and requesting the default
/// transport in a runtime without <c>fetch</c> fails fast (Requirement 6.7).
/// </summary>
/// <remarks>
/// <para>
/// The file content is a fixed constant — this runtime does not vary per document — so the emitter is a pure
/// function of no input and its output is byte-for-byte identical on every run and every operating system
/// (Requirement 9). The content is authored with two-space indentation and normalized to a fixed <c>\n</c>
/// line terminator regardless of how this source file happens to be stored on disk.
/// </para>
/// <para>
/// The emitted TypeScript imports no UI or grid package and depends only on the platform's global
/// <c>fetch</c> and the standard <c>RequestInit</c>/<c>Response</c> DOM types (Requirements 6.4, 12.5, 12.6).
/// It is authored to type-check under the strict harness tsconfig (<c>strict</c>,
/// <c>exactOptionalPropertyTypes</c>, <c>noUncheckedIndexedAccess</c>).
/// </para>
/// <para>
/// The "construction fails if no transport and <c>fetch</c> is unavailable" enforcement (Requirement 6.7)
/// lives at the client-context construction seam, which calls <c>createFetchTransport()</c> when no transport
/// is injected; this file provides that guarded factory (it throws <c>FetchUnavailableError</c> eagerly) plus
/// the convenience <c>fetchTransport</c> singleton that guards lazily at call time.
/// </para>
/// </remarks>
public static class HttpTransportEmitter
{
    /// <summary>The output-relative path of the emitted transport runtime file.</summary>
    public const string RelativePath = "runtime/http-transport.ts";

    /// <summary>
    /// Produces the <see cref="GeneratedFile"/> for <c>runtime/http-transport.ts</c>. The result is
    /// deterministic and independent of any input.
    /// </summary>
    /// <returns>The emitted transport runtime file.</returns>
    public static GeneratedFile Emit() => new(RelativePath, Content);

    /// <summary>The complete, normalized (<c>\n</c>) TypeScript source for the transport runtime file.</summary>
    private static string Content { get; } = Normalize(Source);

    /// <summary>
    /// Normalizes line endings to a fixed <c>\n</c> so the emitted bytes never depend on how this source file
    /// is stored (CRLF vs LF) on the build machine (Requirement 9.1).
    /// </summary>
    private static string Normalize(string text) => text.Replace("\r\n", "\n").Replace("\r", "\n");

    /// <summary>
    /// The authored TypeScript source. Kept as a single raw string literal so the emitted file reads exactly
    /// as it appears here; <see cref="Normalize"/> guarantees the <c>\n</c> line terminator.
    /// </summary>
    private const string Source = """
        // <auto-generated>
        //   This file was generated by the a2n.Vista TypeScript client generator.
        //   Do not edit it by hand: regenerating the client overwrites any local changes.
        // </auto-generated>

        /**
         * A fully composed HTTP request handed to the transport. By the time the client builds an
         * `HttpRequest` the URL is absolute, the headers are final, and the body (when present) is already
         * serialized JSON text, so a transport only has to perform the wire call.
         */
        export interface HttpRequest {
          /** The HTTP method, e.g. `"GET"` or `"POST"`. */
          readonly method: string;
          /** The fully composed, absolute request URL. */
          readonly url: string;
          /** The final request headers to send as-is. */
          readonly headers: Readonly<Record<string, string>>;
          /** The serialized request body as JSON text; `undefined` for bodyless requests such as `GET`. */
          readonly body?: string;
        }

        /**
         * The HTTP response returned by the transport. The body is the raw, unparsed response text; the
         * client is responsible for interpreting it (for example, deserializing success payloads or parsing
         * an RFC 7807 problem document).
         */
        export interface HttpResponse {
          /** The HTTP status code. */
          readonly status: number;
          /** The response headers. The default transport lower-cases header names, per the fetch standard. */
          readonly headers: Readonly<Record<string, string>>;
          /** The raw, unparsed response body text. */
          readonly body: string;
        }

        /**
         * The injectable transport seam. The client routes every request through this abstraction and
         * performs no direct network I/O that bypasses it. Consumers may supply their own implementation to
         * add interceptors, logging, retries, or a test double.
         */
        export interface HttpTransport {
          send(request: HttpRequest): Promise<HttpResponse>;
        }

        /**
         * Thrown when the default `fetch`-backed transport is requested but the platform global `fetch` is
         * unavailable in the current runtime. A client constructed without an explicit transport surfaces this
         * so the failure is diagnosable rather than a late `undefined is not a function`.
         */
        export class FetchUnavailableError extends Error {
          constructor() {
            super(
              "No HttpTransport was supplied and the global fetch API is unavailable in this runtime; " +
                "supply an HttpTransport explicitly.",
            );
            this.name = "FetchUnavailableError";
          }
        }

        /** Reports whether the platform global `fetch` is available in the current runtime. */
        export function isFetchAvailable(): boolean {
          return typeof globalThis.fetch === "function";
        }

        /**
         * Performs a single request via the platform global `fetch`, translating the fetch `Response` into an
         * `HttpResponse` (status, headers as a plain record, body as raw text). Rejects with
         * `FetchUnavailableError` when `fetch` is unavailable. Never retries.
         */
        async function sendViaFetch(request: HttpRequest): Promise<HttpResponse> {
          if (!isFetchAvailable()) {
            throw new FetchUnavailableError();
          }

          const init: RequestInit = {
            method: request.method,
            headers: { ...request.headers },
          };
          if (request.body !== undefined) {
            init.body = request.body;
          }

          const response = await globalThis.fetch(request.url, init);

          const headers: Record<string, string> = {};
          response.headers.forEach((value, key) => {
            headers[key] = value;
          });

          const body = await response.text();

          return {
            status: response.status,
            headers,
            body,
          };
        }

        /**
         * Creates the default transport backed by the platform global `fetch`. Throws `FetchUnavailableError`
         * eagerly when `fetch` is unavailable, so a client constructed without an explicit transport fails at
         * construction time in a runtime that cannot perform requests, rather than on the first call.
         */
        export function createFetchTransport(): HttpTransport {
          if (!isFetchAvailable()) {
            throw new FetchUnavailableError();
          }
          return { send: sendViaFetch };
        }

        /**
         * The default transport instance backed by the platform global `fetch`. It resolves `fetch` lazily at
         * call time; if `fetch` is unavailable the returned promise rejects with `FetchUnavailableError`.
         * Prefer `createFetchTransport()` when you want a client to fail fast at construction.
         */
        export const fetchTransport: HttpTransport = { send: sendViaFetch };
        """;
}
