namespace a2n.Vista.Client.TypeScript.Emit.Runtime;

/// <summary>
/// Emits <c>runtime/raw-payload.ts</c> — the one-line runtime type an <c>export</c> facet's success payload
/// is preserved as (Requirement 4.7). The <c>export</c> operation returns the response body verbatim, as
/// raw, unparsed text, rather than deserializing it into a typed object; that raw body is typed
/// <c>RawPayload</c>.
/// </summary>
/// <remarks>
/// <para>
/// The operation-graph step (<see cref="a2n.Vista.Client.TypeScript.Modeling.OperationGraphBuilder"/>)
/// references this type by name (<c>OperationGraphBuilder.RawPayloadTypeName</c>) as the success type of any
/// facet whose <c>2xx</c> body is an inline, unnamed schema — the <c>export</c> facet's octet-stream payload.
/// This emitter is the single place that <em>declares</em> it, so the per-view client (task 10.6) can import
/// it by name (<c>import type { RawPayload } from "../runtime/raw-payload"</c>).
/// </para>
/// <para>
/// It lives in its own runtime file rather than in <c>runtime/result.ts</c> so the result module (task 10.3)
/// stays untouched, and so the per-view clients depend only on this tiny, dependency-free declaration. The
/// content is a fixed template — it does not vary with the document — so the emitter is a pure function of no
/// input and its output is byte-for-byte identical on every run and operating system (Requirement 9.1). The
/// authored source is normalized to a single <c>\n</c> line terminator with a single trailing newline. The
/// emitted TypeScript imports no UI, grid, or server package (Requirements 6.4, 12.5, 12.6).
/// </para>
/// </remarks>
public static class RawPayloadEmitter
{
    /// <summary>The output-directory-relative path of the emitted file (forward-slash separators).</summary>
    public const string RelativePath = "runtime/raw-payload.ts";

    /// <summary>
    /// Produces the buffered <see cref="GeneratedFile"/> for <c>runtime/raw-payload.ts</c> with a fixed
    /// <c>\n</c> line terminator and a single trailing newline, independent of the host operating system
    /// (Requirement 9.1).
    /// </summary>
    /// <returns>The emitted <c>runtime/raw-payload.ts</c> file.</returns>
    public static GeneratedFile Emit() => new(RelativePath, Content);

    /// <summary>The complete, normalized (<c>\n</c>) TypeScript source for the raw-payload runtime file.</summary>
    private static string Content { get; } = Normalize(Source);

    /// <summary>
    /// Normalizes any line terminator that may have crept in from the source-file checkout (a CRLF on
    /// Windows) to the single fixed <c>\n</c> the generator emits, and guarantees exactly one trailing
    /// newline, so the emitted bytes are identical everywhere (Requirement 9.1).
    /// </summary>
    private static string Normalize(string text)
    {
        var lf = text.Replace("\r\n", "\n", StringComparison.Ordinal).Replace("\r", "\n", StringComparison.Ordinal);
        return lf.EndsWith('\n') ? lf : lf + "\n";
    }

    // The literal is written flush-left so the raw string strips no indentation. English comments only
    // (published artifact).
    private const string Source =
"""
// <auto-generated>
//   This file is generated by the a2n.Vista TypeScript client generator. Do not edit by hand.
//   It defines the raw, unparsed payload type an `export` operation preserves its response body as.
// </auto-generated>

/**
 * The raw, unparsed body of an `export` response (Requirement 4.7). The `export` operation returns the
 * response body verbatim as text rather than deserializing it into a typed object, so a consumer can decode
 * it however the chosen export format requires (for example, CSV or a spreadsheet's bytes as a data URL).
 */
export type RawPayload = string;
""";
}
