namespace a2n.Vista.Client.TypeScript.Emit.Runtime;

/// <summary>
/// Emits <c>runtime/result.ts</c>: the single discriminated <c>ClientResult&lt;T&gt;</c> union that every
/// generated operation returns, the discriminant-driven classification helpers, and the total, never-throws
/// response classifier that maps an HTTP response (status + media type + body) into a <c>ClientResult</c>
/// (Requirements 8.1–8.6; the union also carries the outcomes produced by the client itself — the
/// <c>transport-error</c> for a rejecting transport (6.6), the <c>unauthorized</c> auth short-circuit
/// (7.3/7.4), and the <c>not-found</c>/<c>precondition-*</c> read/write outcomes (4.5, 5.6)).
/// </summary>
/// <remarks>
/// <para>
/// The emitted content is fixed text: it does not vary with the document, so it is trivially deterministic
/// (Requirement 9). The one contract with the rest of the output is the <c>import type</c> of
/// <c>ProblemDetails</c> from the generated <c>types</c> module: this file lives at <c>runtime/result.ts</c>,
/// so the relative import is <c>../types</c>. A type-only import keeps the reference erased at runtime and
/// stays friendly to strict/isolated-modules TypeScript.
/// </para>
/// <para>
/// The classifier deliberately consumes a small structural <c>ClassifiableResponse</c> (status, already
/// resolved content type, raw body) rather than the transport's <c>HttpResponse</c>, so the header
/// representation stays the transport module's concern and this module has no dependency on it. The
/// per-view client adapts its transport response into that shape at the call site.
/// </para>
/// </remarks>
public static class ResultEmitter
{
    /// <summary>The output-directory-relative path of the emitted file (forward slashes, Requirement 9.1).</summary>
    public const string RelativePath = "runtime/result.ts";

    /// <summary>
    /// Produces the buffered <see cref="GeneratedFile"/> for <c>runtime/result.ts</c> with a fixed
    /// <c>\n</c> line terminator, independent of the host operating system (Requirement 9.1).
    /// </summary>
    public static GeneratedFile Emit() => new(RelativePath, Normalize(RawContent));

    /// <summary>
    /// Normalizes any line terminator that may have crept in from the source-file checkout (a CRLF on
    /// Windows) to the single fixed <c>\n</c> the generator emits, so the bytes are identical everywhere.
    /// </summary>
    private static string Normalize(string text) =>
        text.Replace("\r\n", "\n", StringComparison.Ordinal).Replace("\r", "\n", StringComparison.Ordinal);

    // The literal is written flush-left so the raw string strips no indentation; the TypeScript's own
    // 2-space indentation is preserved verbatim. English comments only (published artifact).
    private const string RawContent =
"""
// <auto-generated>
//   This file is generated by the a2n.Vista TypeScript client generator. Do not edit by hand.
//   It defines the single typed outcome every generated operation returns and the total classifier
//   that maps an HTTP response into that outcome without ever throwing.
// </auto-generated>

import type { ProblemDetails } from "../types";

/**
 * The single discriminated outcome of every client operation (Requirement 8.4). A consumer inspects the
 * one `kind` discriminant to handle the outcome — never the raw HTTP status, and never a thrown error.
 *
 * - `success`               a 2xx response, body deserialized into the operation's success type `T`.
 * - `problem`               an RFC 7807 `application/problem+json` failure not covered by a specialized kind.
 * - `unauthorized`          the client short-circuited before sending (no/failed credential on a secured op).
 * - `not-found`             a 404 problem response (e.g. `detail` for a missing key).
 * - `precondition-required` a 428 problem response (a concurrency token was required but not supplied).
 * - `precondition-failed`   a 409 problem response (the supplied concurrency token did not match).
 * - `transport-error`       the injected transport rejected or threw; no retry is attempted.
 * - `unexpected`            any other response: a non-2xx non-problem body, or a body that failed to parse.
 */
export type ClientResult<T> =
  | { readonly kind: "success"; readonly value: T }
  | { readonly kind: "problem"; readonly status: number; readonly problem: ProblemDetails }
  | { readonly kind: "unauthorized"; readonly reason: string }
  | { readonly kind: "not-found"; readonly status: 404; readonly problem: ProblemDetails }
  | { readonly kind: "precondition-required"; readonly status: 428; readonly problem: ProblemDetails }
  | { readonly kind: "precondition-failed"; readonly status: 409; readonly problem: ProblemDetails }
  | { readonly kind: "transport-error"; readonly error: unknown }
  | { readonly kind: "unexpected"; readonly status: number; readonly rawBody: string };

/** The set of discriminant values a {@link ClientResult} can carry, derived from the single `kind` field. */
export type ClientResultKind = ClientResult<unknown>["kind"];

/**
 * The minimal, transport-agnostic view of an HTTP response the classifier needs. The per-view client
 * builds this from its transport's response, resolving the `Content-Type` header into `contentType`
 * (or `null` when absent) so this module stays independent of any particular header representation.
 */
export interface ClassifiableResponse {
  readonly status: number;
  readonly contentType: string | null;
  readonly body: string;
}

// --- Constructors -------------------------------------------------------------------------------------
// Small helpers so the client and the classifier build outcomes the same way, keeping the `kind`
// discriminant the single source of truth.

/** Builds a `success` outcome carrying the typed payload (Requirement 8.1). */
export function success<T>(value: T): ClientResult<T> {
  return { kind: "success", value };
}

/**
 * Builds an `unauthorized` outcome. The client uses this to short-circuit a secured operation before
 * sending when no credential is available or the auth provider failed (Requirements 7.3, 7.4).
 */
export function unauthorized<T = never>(reason: string): ClientResult<T> {
  return { kind: "unauthorized", reason };
}

/**
 * Builds a `transport-error` outcome. The client uses this when the injected transport rejects or throws;
 * the failure is surfaced as a result with no automatic retry (Requirement 6.6).
 */
export function transportError<T = never>(error: unknown): ClientResult<T> {
  return { kind: "transport-error", error };
}

// --- Classification helpers ---------------------------------------------------------------------------
// Every helper is driven solely by the one `kind` discriminant.

/** Narrows to the successful outcome. */
export function isSuccess<T>(result: ClientResult<T>): result is Extract<ClientResult<T>, { kind: "success" }> {
  return result.kind === "success";
}

/** True for any non-success outcome. */
export function isFailure<T>(result: ClientResult<T>): boolean {
  return result.kind !== "success";
}

/** Narrows to the generic RFC 7807 problem outcome. */
export function isProblem<T>(result: ClientResult<T>): result is Extract<ClientResult<T>, { kind: "problem" }> {
  return result.kind === "problem";
}

/** Narrows to the unauthorized short-circuit outcome. */
export function isUnauthorized<T>(
  result: ClientResult<T>,
): result is Extract<ClientResult<T>, { kind: "unauthorized" }> {
  return result.kind === "unauthorized";
}

/** Narrows to the 404 not-found problem outcome. */
export function isNotFound<T>(result: ClientResult<T>): result is Extract<ClientResult<T>, { kind: "not-found" }> {
  return result.kind === "not-found";
}

/** Narrows to the 428 precondition-required problem outcome. */
export function isPreconditionRequired<T>(
  result: ClientResult<T>,
): result is Extract<ClientResult<T>, { kind: "precondition-required" }> {
  return result.kind === "precondition-required";
}

/** Narrows to the 409 precondition-failed problem outcome. */
export function isPreconditionFailed<T>(
  result: ClientResult<T>,
): result is Extract<ClientResult<T>, { kind: "precondition-failed" }> {
  return result.kind === "precondition-failed";
}

/** Narrows to the transport-error outcome. */
export function isTransportError<T>(
  result: ClientResult<T>,
): result is Extract<ClientResult<T>, { kind: "transport-error" }> {
  return result.kind === "transport-error";
}

/** Narrows to the catch-all unexpected outcome. */
export function isUnexpected<T>(
  result: ClientResult<T>,
): result is Extract<ClientResult<T>, { kind: "unexpected" }> {
  return result.kind === "unexpected";
}

/**
 * Tests whether a `Content-Type` value denotes RFC 7807 problem JSON, matching case-insensitively and
 * ignoring media type parameters such as `charset` (Requirement 8.2). A `null`/absent content type is
 * treated as not problem JSON.
 */
export function isProblemJson(contentType: string | null): boolean {
  if (contentType === null) {
    return false;
  }
  const essence = contentType.split(";", 1)[0].trim().toLowerCase();
  return essence === "application/problem+json";
}

/**
 * The total response classifier: maps an HTTP response into a {@link ClientResult}, and never throws
 * (Requirements 8.1–8.6). It is generic over the success type `T`; the caller supplies `parseSuccess`
 * to deserialize a 2xx body into `T`.
 *
 * Classification, in order:
 * 1. `2xx`                              -> deserialize the body with `parseSuccess` into `success`
 *                                          (8.1); a parse failure degrades to `unexpected` (8.5).
 * 2. `application/problem+json`         -> parse `ProblemDetails`, then map by status: 404 -> `not-found`,
 *                                          428 -> `precondition-required`, 409 -> `precondition-failed`,
 *                                          otherwise -> `problem` (8.2); a parse failure degrades to
 *                                          `unexpected` (8.6).
 * 3. any other non-2xx response         -> `unexpected` carrying the status and the raw body (8.3).
 */
export function classifyResponse<T>(
  response: ClassifiableResponse,
  parseSuccess: (body: string) => T,
): ClientResult<T> {
  const { status, contentType, body } = response;

  if (status >= 200 && status <= 299) {
    try {
      return { kind: "success", value: parseSuccess(body) };
    } catch {
      return { kind: "unexpected", status, rawBody: body };
    }
  }

  if (isProblemJson(contentType)) {
    let problem: ProblemDetails;
    try {
      problem = parseProblemDetails(body);
    } catch {
      return { kind: "unexpected", status, rawBody: body };
    }

    switch (status) {
      case 404:
        return { kind: "not-found", status: 404, problem };
      case 428:
        return { kind: "precondition-required", status: 428, problem };
      case 409:
        return { kind: "precondition-failed", status: 409, problem };
      default:
        return { kind: "problem", status, problem };
    }
  }

  return { kind: "unexpected", status, rawBody: body };
}

/**
 * Parses a response body into a {@link ProblemDetails}. Throws when the body is not a JSON object, letting
 * {@link classifyResponse} translate the failure into an `unexpected` outcome (Requirement 8.6). This is
 * the only place JSON parsing can throw, and every caller wraps it.
 */
function parseProblemDetails(body: string): ProblemDetails {
  const parsed: unknown = JSON.parse(body);
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new TypeError("Problem response body is not a JSON object.");
  }
  return parsed as ProblemDetails;
}
""";
}
