namespace a2n.Vista.Client.TypeScript.Emit.Runtime;

/// <summary>
/// Emits the framework-agnostic <c>runtime/url.ts</c> file of the generated client: the single-slash base
/// URL + operation path join and the base-URL validation that the client context consumes at construction.
/// </summary>
/// <remarks>
/// <para>
/// The emitted module contains no per-document information — it is a fixed runtime the client depends on —
/// so its content is a constant and inherently deterministic (Requirement 9.1). The output uses the
/// generator's single fixed <c>\n</c> line terminator and two-space indentation regardless of the host
/// operating system's newline convention.
/// </para>
/// <para>
/// The emitted helpers implement four acceptance criteria:
/// </para>
/// <list type="bullet">
///   <item>
///     <description>
///     <c>joinUrl</c> joins the base URL and an operation path with exactly one <c>/</c> separator,
///     collapsing any duplicate slash introduced at the join while preserving the path's own internal
///     segments (Requirement 6.3).
///     </description>
///   </item>
///   <item>
///     <description>
///     <c>validateBaseUrl</c> rejects an absent, empty, or syntactically invalid absolute base URL with a
///     typed <c>error</c> outcome (Requirement 6.5).
///     </description>
///   </item>
///   <item>
///     <description>
///     A non-HTTPS scheme over a loopback host (<c>localhost</c>, <c>127.0.0.1</c>, <c>::1</c>) yields a
///     <c>warn</c> outcome so the client context can warn and still complete construction (Requirement 7.6).
///     </description>
///   </item>
///   <item>
///     <description>
///     A non-HTTPS scheme over a non-loopback host yields a typed <c>error</c> outcome so the client
///     context fails construction and issues no request (Requirement 7.7).
///     </description>
///   </item>
/// </list>
/// <para>
/// The <see cref="BaseUrlValidation"/> discriminated result (a union keyed on <c>kind</c>) is the clean
/// seam the client-context emitter consumes: it fails construction on <c>error</c>, warns and continues on
/// <c>warn</c>, and proceeds on <c>ok</c> — no exception-driven control flow.
/// </para>
/// </remarks>
public static class UrlEmitter
{
    /// <summary>The output-relative path of the emitted URL runtime module.</summary>
    public const string RelativePath = "runtime/url.ts";

    /// <summary>
    /// Builds the <see cref="GeneratedFile"/> for <c>runtime/url.ts</c>. The content is constant, uses
    /// <c>\n</c> line terminators, and always ends with a single trailing newline.
    /// </summary>
    /// <returns>The emitted <c>runtime/url.ts</c> file.</returns>
    public static GeneratedFile Emit() => new(RelativePath, Content);

    /// <summary>
    /// The rendered TypeScript source, normalized to <c>\n</c> line terminators with a single trailing
    /// newline so the emitted bytes are identical on every operating system (Requirement 9.1).
    /// </summary>
    private static string Content => Normalize(RawContent);

    /// <summary>
    /// Normalizes any source-file line endings to the generator's single fixed <c>\n</c> terminator and
    /// guarantees exactly one trailing newline, so the emitted bytes never depend on how this C# file was
    /// saved.
    /// </summary>
    private static string Normalize(string content)
    {
        var lf = content.Replace("\r\n", "\n").Replace("\r", "\n");
        return lf.EndsWith('\n') ? lf : lf + "\n";
    }

    private const string RawContent = """
// <auto-generated>
//   This file is generated by the a2n.Vista TypeScript client generator.
//   Do not edit by hand; regenerate it from the OpenAPI document instead.
// </auto-generated>
//
// Base-URL join and validation helpers for the generated client. These functions are
// framework-agnostic and rely only on the global `URL` constructor for parsing and validation.

/**
 * The outcome of validating a base URL supplied at client construction, discriminated on `kind`:
 * - `ok`    the URL is a valid absolute HTTPS URL; construction may proceed.
 * - `warn`  the URL is a valid non-HTTPS loopback URL; construction may proceed, but a warning applies.
 * - `error` the URL is absent, empty, syntactically invalid, or a non-HTTPS non-loopback URL;
 *           construction must fail and no request may be issued.
 */
export type BaseUrlValidation =
  | { readonly kind: "ok"; readonly url: string }
  | { readonly kind: "warn"; readonly url: string; readonly warning: string }
  | { readonly kind: "error"; readonly error: string };

/**
 * The loopback hosts permitted to use a non-HTTPS scheme. A non-HTTPS base URL is accepted with a
 * warning only when its host is one of these; every other non-HTTPS host is rejected.
 */
const loopbackHosts: ReadonlySet<string> = new Set<string>(["localhost", "127.0.0.1", "::1"]);

/**
 * Joins a base URL and an operation path using exactly one `/` separator. Any trailing `/` on the base
 * and any leading `/` on the path are collapsed at the join, while the path's own internal segments are
 * preserved. An empty path (after trimming leading slashes) yields the base URL unchanged.
 */
export function joinUrl(baseUrl: string, path: string): string {
  const base = baseUrl.replace(/\/+$/, "");
  const suffix = path.replace(/^\/+/, "");
  return suffix.length === 0 ? base : `${base}/${suffix}`;
}

/**
 * Removes a single pair of surrounding brackets from an IPv6 host (e.g. `[::1]` -> `::1`) so it can be
 * compared against the loopback host set; other hosts are returned unchanged.
 */
function normalizeHost(hostname: string): string {
  return hostname.startsWith("[") && hostname.endsWith("]") ? hostname.slice(1, -1) : hostname;
}

/**
 * Validates a base URL for client construction and classifies the outcome:
 * - absent, empty, or not a syntactically valid absolute URL -> `error` (construction fails).
 * - non-HTTPS scheme over a loopback host -> `warn` (construction may proceed with a warning).
 * - non-HTTPS scheme over a non-loopback host -> `error` (construction fails).
 * - HTTPS -> `ok`.
 */
export function validateBaseUrl(baseUrl: string): BaseUrlValidation {
  if (typeof baseUrl !== "string" || baseUrl.trim().length === 0) {
    return { kind: "error", error: "The base URL is absent or empty." };
  }

  let parsed: URL;
  try {
    parsed = new URL(baseUrl);
  } catch {
    return {
      kind: "error",
      error: `The base URL "${baseUrl}" is not a syntactically valid absolute URL.`,
    };
  }

  if (parsed.protocol === "https:") {
    return { kind: "ok", url: baseUrl };
  }

  const scheme = parsed.protocol.replace(/:$/, "");
  if (loopbackHosts.has(normalizeHost(parsed.hostname).toLowerCase())) {
    return {
      kind: "warn",
      url: baseUrl,
      warning: `The base URL "${baseUrl}" uses the non-HTTPS scheme "${scheme}" over a loopback host; traffic will not be encrypted in transit.`,
    };
  }

  return {
    kind: "error",
    error: `The base URL "${baseUrl}" uses the non-HTTPS scheme "${scheme}" over a non-loopback host; use HTTPS for non-loopback hosts.`,
  };
}
""";
}
