using System.Text;
using a2n.Vista.Client.TypeScript.Emit.Runtime;

namespace a2n.Vista.Client.TypeScript.Emit;

/// <summary>
/// Emits the deterministic <c>index.ts</c> barrel (task 10.8; design §A.7 <c>IndexEmitter</c>): a single
/// entry module that re-exports the whole <see cref="GeneratedFile">Generated_Output</see> surface —
/// <c>types.ts</c>, <c>filter-node.ts</c>, the framework-agnostic runtime modules, and every per-view client
/// under <c>views/</c> — so a consumer imports the entire client from one path (Requirement 9.1).
/// </summary>
/// <remarks>
/// <para>
/// <b>Only relative re-exports.</b> The barrel emits nothing but <c>export * from "./…";</c> lines against
/// the sibling generated modules. It declares no value, imports no UI or grid package, and embeds no
/// credential, so it inherits the secure-by-default, framework-agnostic posture of the modules it re-exports
/// (Requirements 7.1, 12.3, 12.5, 12.6).
/// </para>
/// <para>
/// <b>Export-name collisions.</b> A <c>export *</c> from several modules is only safe when the modules'
/// exported names are disjoint. They are, by design: every generated type is declared exactly once and
/// referenced by name (Requirement 2.5), the runtime modules export distinct contracts, each per-view client
/// exports a uniquely-named <c>{View}Client</c> class (its view names are globally unique), and every
/// module-private helper (for example the view files' <c>readContentType</c>) is left un-exported. So the
/// wildcard re-exports never clash.
/// </para>
/// <para>
/// <b>Determinism (Requirement 9).</b> Every module specifier — the fixed modules and the per-view modules
/// alike — is collected into one set and ordered by a single ordinal, case-sensitive comparison via
/// <see cref="DeterministicOrder"/>, independent of the order the views arrive in or the host operating
/// system. The per-view file stems are derived through <see cref="ViewClientEmitter.FileName"/>, the same
/// transform the view-client emitter uses, so the barrel and the files it points at always agree. The output
/// uses a fixed <c>\n</c> line terminator with a single trailing newline. The emitter reads only its inputs
/// and performs no I/O.
/// </para>
/// </remarks>
public static class IndexEmitter
{
    /// <summary>The output-directory-relative path of the emitted barrel (forward slashes, Requirement 9.1).</summary>
    public const string RelativePath = "index.ts";

    /// <summary>The fixed <c>\n</c> line terminator for emitted source (Requirement 9.1).</summary>
    private const string NewLine = "\n";

    /// <summary>
    /// The fixed module specifiers the barrel always re-exports: the two type modules plus the runtime
    /// modules. These are constant regardless of the document, and are ordered alongside the per-view
    /// modules by the shared deterministic comparison before emission.
    /// </summary>
    private static readonly IReadOnlyList<string> FixedModules =
    [
        "./" + StripExtension(TypesEmitter.RelativePath),
        "./" + StripExtension(FilterNodeEmitter.RelativePath),
        "./" + StripExtension(HttpTransportEmitter.RelativePath),
        "./" + StripExtension(AuthEmitter.RelativePath),
        "./" + StripExtension(ResultEmitter.RelativePath),
        "./" + StripExtension(UrlEmitter.RelativePath),
        "./" + StripExtension(ClientContextEmitter.RelativePath),
        "./" + StripExtension(RawPayloadEmitter.RelativePath),
    ];

    private const string Header =
        "// <auto-generated>\n" +
        "//   This file is generated by the a2n.Vista TypeScript client generator. Do not edit by hand.\n" +
        "//   It is the barrel entry point: it re-exports the generated types, the framework-agnostic\n" +
        "//   runtime, and every per-view client so the whole client can be imported from one path.\n" +
        "// </auto-generated>";

    /// <summary>
    /// Produces the buffered <see cref="GeneratedFile"/> for <c>index.ts</c>: the header comment followed by
    /// one <c>export * from "./…";</c> line per generated module, ordered deterministically
    /// (Requirement 9.2).
    /// </summary>
    /// <param name="viewNames">
    /// The verbatim view names whose <c>views/{stem}.ts</c> clients are re-exported; their kebab-case file
    /// stems are derived via <see cref="ViewClientEmitter.FileName"/>. May be empty (a document with no
    /// mapped view) — then only the fixed modules are re-exported.
    /// </param>
    /// <returns>The emitted <c>index.ts</c> barrel file.</returns>
    public static GeneratedFile Emit(IEnumerable<string> viewNames)
    {
        ArgumentNullException.ThrowIfNull(viewNames);

        // Collect every module specifier — fixed + per-view — into one set, deduplicated, then order the
        // whole set by the single ordinal comparison so the fixed and per-view lines interleave in one
        // stable total order (Requirement 9.2).
        var specifiers = new HashSet<string>(DeterministicOrder.Comparer);
        foreach (var module in FixedModules)
        {
            specifiers.Add(module);
        }

        foreach (var viewName in viewNames)
        {
            specifiers.Add("./views/" + ViewClientEmitter.FileName(viewName));
        }

        var ordered = DeterministicOrder.OrderNames(specifiers);

        var builder = new StringBuilder();
        builder.Append(Header).Append(NewLine);
        builder.Append(NewLine);
        foreach (var specifier in ordered)
        {
            builder.Append($"export * from \"{specifier}\";").Append(NewLine);
        }

        return new GeneratedFile(RelativePath, builder.ToString());
    }

    // Drops the ".ts" extension from a generated module's relative path so it becomes a TypeScript module
    // specifier (extensionless, matching the sibling emitters' import specifiers).
    private static string StripExtension(string relativePath) =>
        relativePath.EndsWith(".ts", StringComparison.Ordinal)
            ? relativePath[..^3]
            : relativePath;
}
