using System.Text;
using a2n.Vista.Client.TypeScript.Modeling;
using a2n.Vista.Client.TypeScript.Pipeline;
using a2n.Vista.Client.TypeScript.Resolve;

namespace a2n.Vista.Client.TypeScript.Emit;

/// <summary>
/// Emits <c>types.ts</c> (task 9.2; design "Generated output layout"): the fixed Vista request/response
/// envelopes, the RFC 7807 <c>ProblemDetails</c> with the document-declared nullability/optionality, each
/// per-view row/write DTO, and — declared exactly once — the single generic
/// <c>ViewListResult&lt;TRow&gt;</c> / <c>PagedResult&lt;TRow&gt;</c> result types. Every type is declared
/// once and referenced by name (Requirements 2.1, 2.4, 2.5, 2.6, 3.1–3.4).
/// </summary>
/// <remarks>
/// <para>
/// <b>What lives here vs. elsewhere.</b> The presence-discriminated <c>FilterNode</c> family and the
/// <c>FilterOperator</c> literal union live in a separate file (<c>filter-node.ts</c>, task 9.3). This
/// emitter therefore never declares them; when an envelope references one (for example
/// <c>VistaListRequestBody.filter</c>/<c>scope</c> → <c>FilterNode</c>), a single
/// <c>import type { … } from "./filter-node"</c> is emitted at the top of the file so every referenced type
/// is still reachable by name (Requirement 2.5). The monomorphized <c>ViewListResult_*</c> components are
/// re-lifted (collapsed) into the generic pair and are <b>not</b> emitted per view; only the re-lifter's
/// reported fallback components (a shape it could not recognize) are emitted as plain interfaces so their
/// members are preserved.
/// </para>
/// <para>
/// <b>How the declarations are built.</b> Every object type — envelopes, <c>ProblemDetails</c>, per-view
/// DTOs, and fallback components — is turned into a <see cref="TsTypeDecl"/> by
/// <see cref="DtoModelBuilder"/>, so property names stay verbatim (Requirement 3.1), string enums become
/// literal unions in document order (Requirement 3.2), nullable members include <c>null</c> (Requirement
/// 3.3), members absent from <c>required</c> are optional (Requirement 3.4), and each declaration's members
/// stay in the deterministic by-name order the DTO builder produces (Requirement 9.2). The two generic
/// result types are hand-built from their fixed shapes (their members do not vary with the document) and
/// their members are likewise ordered by name.
/// </para>
/// <para>
/// <b>Determinism (Requirement 9).</b> The top-level declarations are ordered by declared name via
/// <see cref="DeterministicOrder"/>, each declared exactly once (deduplicated by name, Requirement 2.1),
/// separated by a single blank line, with <c>\n</c> line terminators throughout, independent of the
/// document's enumeration order. The emitter reads only the in-memory model and performs no I/O.
/// </para>
/// <para>
/// <b>Failure.</b> A per-view DTO or fallback component absent from <c>components.schemas</c> is a fatal
/// <see cref="GenerationError.MissingSchema"/> (Requirement 2.7), returned (never thrown) so the buffered
/// pipeline routes it through the single abort path. The bound envelopes are already known-present (the
/// <see cref="EnvelopeCatalog"/> bound them), so they never fail here.
/// </para>
/// </remarks>
public static class TypesEmitter
{
    /// <summary>The output-directory-relative path of the emitted file (forward slashes, Requirement 9.1).</summary>
    public const string RelativePath = "types.ts";

    /// <summary>The relative module specifier of the cross-file <c>filter-node.ts</c> module (task 9.3).</summary>
    private const string FilterNodeModule = "./filter-node";

    /// <summary>The fixed <c>\n</c> line terminator for emitted source (Requirement 9.1).</summary>
    private const string NewLine = "\n";

    /// <summary>The fixed indent applied to a generic type's member lines — two spaces, matching the emitter convention.</summary>
    private const string MemberIndent = "  ";

    /// <summary>
    /// The set of type names that are declared in the sibling <c>filter-node.ts</c> module (task 9.3), not
    /// here. Any reference to one of these from a type this file emits is satisfied by an
    /// <c>import type</c> from <see cref="FilterNodeModule"/>.
    /// </summary>
    private static readonly IReadOnlySet<string> FilterNodeModuleExports = new HashSet<string>(StringComparer.Ordinal)
    {
        FilterNodeModelBuilder.FilterNodeName,
        FilterNodeModelBuilder.FilterOperatorName,
        "FilterLeaf",
        "FilterAnd",
        "FilterOr",
        "FilterNot",
    };

    private const string Header =
        "// <auto-generated>\n" +
        "//   This file is generated by the a2n.Vista TypeScript client generator. Do not edit by hand.\n" +
        "//   It declares the fixed Vista envelopes, ProblemDetails, the per-view row/write DTOs, and the\n" +
        "//   single generic ViewListResult<TRow>/PagedResult<TRow> result types. Each type is declared\n" +
        "//   exactly once and referenced by name; the FilterNode family lives in ./filter-node.\n" +
        "// </auto-generated>";

    /// <summary>
    /// Produces the buffered <see cref="GeneratedFile"/> for <c>types.ts</c> from the supplied inputs, or a
    /// fatal <see cref="GenerationError.MissingSchema"/> for the first per-view DTO or fallback component
    /// absent from <c>components.schemas</c> (Requirement 2.7).
    /// </summary>
    /// <param name="input">The emit inputs (resolved document, bound envelopes, re-lift result, DTO names, notices).</param>
    /// <returns>
    /// <see cref="Result{T, E}.Ok"/> carrying the emitted <c>types.ts</c> file when every referenced
    /// component is present; otherwise <see cref="Result{T, E}.Err"/> carrying the first missing schema.
    /// </returns>
    public static Result<GeneratedFile, GenerationError> Emit(TypesEmitInput input)
    {
        ArgumentNullException.ThrowIfNull(input);

        var builder = new DtoModelBuilder();

        // Declarations keyed by name so a type can never be declared twice (Requirement 2.1). Envelopes,
        // per-view DTOs, and re-lift fallbacks are disjoint by construction, but deduplicating by name makes
        // the "declared once" invariant structural rather than merely conventional.
        var declsByName = new Dictionary<string, TsTypeDecl>(DeterministicOrder.Comparer);

        // 1. The fixed Vista envelopes (including ProblemDetails). The catalog already bound these, so they
        //    are known-present; building them here maps each envelope's schema through the DTO builder,
        //    honoring the document-declared nullability/optionality (Requirements 2.1, 2.4).
        foreach (var name in input.Envelopes.BoundNames)
        {
            var result = builder.BuildDecl(name, input.Document, input.Notices);
            if (result.IsError)
            {
                return Result<GeneratedFile, GenerationError>.Err(result.Error);
            }

            declsByName[name] = result.Value;
        }

        // 2. The per-view row/write DTO components supplied by the pipeline (from each ViewModel's
        //    RowType/CrudType). A component absent from the document is fatal (Requirement 2.7).
        foreach (var name in input.DtoComponentNames)
        {
            if (declsByName.ContainsKey(name))
            {
                continue;
            }

            var result = builder.BuildDecl(name, input.Document, input.Notices);
            if (result.IsError)
            {
                return Result<GeneratedFile, GenerationError>.Err(result.Error);
            }

            declsByName[name] = result.Value;
        }

        // 3. The re-lifter's fallback components — monomorphized ViewListResult_* shapes it could not
        //    collapse to the generic pair — are emitted as plain named interfaces so their members are
        //    preserved (design "Error Handling").
        foreach (var name in input.ReLift.FallbackComponents)
        {
            if (declsByName.ContainsKey(name))
            {
                continue;
            }

            var result = builder.BuildDecl(name, input.Document, input.Notices);
            if (result.IsError)
            {
                return Result<GeneratedFile, GenerationError>.Err(result.Error);
            }

            declsByName[name] = result.Value;
        }

        // 4. The single generic result pair, declared once, only when a list envelope was recognized
        //    (Requirements 2.6, 2.5).
        if (input.ReLift.GenericEnvelopesNeeded)
        {
            var pagedResult = BuildPagedResultDecl();
            var viewListResult = BuildViewListResultDecl();
            declsByName[pagedResult.Name] = pagedResult;
            declsByName[viewListResult.Name] = viewListResult;
        }

        // Order all top-level declarations by name (Requirement 9.2). Members within each are already
        // by-name ordered by the DTO builder (and by construction for the generics).
        var orderedDecls = DeterministicOrder.ByName(declsByName.Values, decl => decl.Name);

        var content = Render(orderedDecls);
        return Result<GeneratedFile, GenerationError>.Ok(new GeneratedFile(RelativePath, content));
    }

    // Renders the whole file: header, an optional cross-file import, then the declarations, each separated
    // by a single blank line, with a single trailing newline.
    private static string Render(IReadOnlyList<TsTypeDecl> decls)
    {
        var sections = new List<string> { Header };

        var importLine = BuildFilterNodeImport(decls);
        if (importLine is not null)
        {
            sections.Add(importLine);
        }

        foreach (var decl in decls)
        {
            sections.Add(decl.Render());
        }

        // A single blank line between sections, and a trailing newline so the file ends cleanly.
        return string.Join(NewLine + NewLine, sections) + NewLine;
    }

    // Builds the `import type { … } from "./filter-node";` line for exactly the filter-node types the
    // emitted declarations reference, in deterministic order — or null when none are referenced.
    private static string? BuildFilterNodeImport(IReadOnlyList<TsTypeDecl> decls)
    {
        var referenced = new HashSet<string>(StringComparer.Ordinal);
        foreach (var decl in decls)
        {
            foreach (var member in decl.Members)
            {
                CollectNamedReferences(member.Type, referenced);
            }
        }

        var imported = DeterministicOrder.OrderNames(referenced.Where(FilterNodeModuleExports.Contains));
        if (imported.Count == 0)
        {
            return null;
        }

        return $"import type {{ {string.Join(", ", imported)} }} from \"{FilterNodeModule}\";";
    }

    // Walks a type expression, collecting every named/generic type reference into the accumulator so the
    // caller can determine which cross-file names must be imported.
    private static void CollectNamedReferences(TsType type, ISet<string> accumulator)
    {
        switch (type)
        {
            case TsNamed named:
                accumulator.Add(named.Name);
                break;

            case TsArray array:
                CollectNamedReferences(array.Element, accumulator);
                break;

            case TsNullable nullable:
                CollectNamedReferences(nullable.Inner, accumulator);
                break;

            case TsGeneric generic:
                accumulator.Add(generic.Name);
                foreach (var argument in generic.Arguments)
                {
                    CollectNamedReferences(argument, accumulator);
                }

                break;

            // Primitives and literal unions carry no named reference.
            default:
                break;
        }
    }

    // The single generic `PagedResult<TRow>` (design "Envelope recognition / generic re-lifting"): a page
    // of `TRow` rows plus the fixed paging counters. Members ordered by name (Requirement 9.2).
    private static TsTypeDecl BuildPagedResultDecl()
    {
        var members = new[]
        {
            new TsProperty("items", TsType.ArrayOf(TsType.Named(RowTypeParameter)), Optional: false),
            new TsProperty("totalRows", TsType.Number, Optional: false),
            new TsProperty("pageIndex", TsType.Number, Optional: false),
            new TsProperty("pageSize", TsType.Number, Optional: false),
            new TsProperty("totalPages", TsType.Number, Optional: false),
        };

        var ordered = DeterministicOrder.ByName(members, member => member.Name);
        return new TsTypeDecl(EnvelopeReLifter.GenericPagedResultName, ordered, new[] { RowTypeParameter });
    }

    // The single generic `ViewListResult<TRow>` (design "Envelope recognition / generic re-lifting"): the
    // re-lifted paged result plus the unfiltered total. Members ordered by name (Requirement 9.2).
    private static TsTypeDecl BuildViewListResultDecl()
    {
        var pagedResult = TsType.Generic(
            EnvelopeReLifter.GenericPagedResultName,
            new[] { TsType.Named(RowTypeParameter) });

        var members = new[]
        {
            new TsProperty("page", pagedResult, Optional: false),
            new TsProperty("totalRowsUnfiltered", TsType.Number, Optional: false),
        };

        var ordered = DeterministicOrder.ByName(members, member => member.Name);
        return new TsTypeDecl(EnvelopeReLifter.GenericViewListResultName, ordered, new[] { RowTypeParameter });
    }

    /// <summary>The single generic row type parameter name shared by the two re-lifted result types.</summary>
    private const string RowTypeParameter = "TRow";
}

/// <summary>
/// The clean input contract the pipeline (task 12.2) hands the <see cref="TypesEmitter"/>. It carries the
/// resolved document (the schema oracle the DTO builder binds against), the fixed envelopes already located
/// by the <see cref="EnvelopeCatalog"/>, the envelope re-lift outcome (which drives the single generic pair
/// and any fallback components), the exact set of per-view row/write DTO component names to emit (derived by
/// the pipeline from the <c>ViewModel</c>s' <c>RowType</c>/<c>CrudType</c>), and the notice collector.
/// </summary>
/// <param name="Document">The resolved document whose schema graph the DTO builder binds against.</param>
/// <param name="Envelopes">The fixed Vista envelopes bound by the <see cref="EnvelopeCatalog"/>.</param>
/// <param name="ReLift">The envelope generic re-lift outcome (generics needed + fallback components).</param>
/// <param name="DtoComponentNames">
/// The per-view row/write DTO component names to emit as interfaces (from the <c>ViewModel</c>s).
/// </param>
/// <param name="Notices">The collector that receives any non-fatal degradation notice.</param>
public sealed record TypesEmitInput(
    ResolvedDocument Document,
    EnvelopeBindings Envelopes,
    EnvelopeReLiftResult ReLift,
    IReadOnlyCollection<string> DtoComponentNames,
    NoticeCollector Notices);
