// Licensed to the a2n.Vista project. Published artifact — English only.
//
// The adapter-endpoint-absence property test for the OpenAPI emitter (spec openapi-emitter, task 9.6;
// Property 10; Requirement 12.1). The live route table (IViewRegistry) + the fixed facet table are the
// oracle: for ANY generated registry — INCLUDING views flagged as adapter-bearing — the emitted document
// must document ONLY the core View_Operation_Set and NEVER a grid-adapter endpoint
// (POST/GET {route}/{RouteSuffix}, D111–D116, e.g. "/datatable" or "/querybuilder").
//
// By-construction guarantee (R12.1): adapters are NOT a builder input in v1. The builder only ever iterates
// the seven core facets (list/detail/metadata/export/create/update/delete) and has no adapter surface on
// ViewMetadata / the builder inputs, so grid-adapter endpoints are not representable through the current
// registry+builder. The generator carries a "has adapters" flag as a no-op MARKER
// (GeneratedRegistry.AdapterViewNames); this property asserts that even adapter-FLAGGED views yield only
// core facets — the emitter is adapter-free by construction, not by filtering.
//
// The property therefore asserts, over every emitted operation:
//   (1) the last path segment (the facet suffix) is one of the seven core facet suffixes — never an
//       adapter RouteSuffix; equivalently, the set of emitted suffixes ⊆ the seven core facets; and
//   (2) the path is exactly a registered view's Route followed by "/" + a core facet — no orphan or
//       adapter path escapes the View_Operation_Set.
// On any violation it throws a descriptive message (the offending path/suffix, plus the adapter-flagged
// views) so CsCheck shrinks to a minimal counterexample.
//
// Build() is [RequiresUnreferencedCode] because it collects per-view DTO schemas by reflecting over the
// row/write CLR types; adapter absence is purely structural, but building the whole document drives that
// reflection branch, so the trim warning is suppressed at the class level (matching the sibling suites).

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using a2n.Vista.AspNetCore.Configuration;
using a2n.Vista.OpenApi;
using a2n.Vista.OpenApi.Model;
using CsCheck;
using TUnit.Core;

namespace a2n.Vista.Tests;

/// <summary>
/// Property-based test for adapter-endpoint absence — Property 10 of the OpenAPI emitter (spec
/// openapi-emitter, task 9.6; Requirement 12.1). Over random registries generated by
/// <see cref="RegistryGenerators.Registry(int, int)"/> — including views flagged as adapter-bearing — it
/// builds the document and asserts that every emitted operation path ends in one of the seven core facet
/// suffixes (never a grid-adapter <c>RouteSuffix</c>) and sits exactly at a registered view's
/// <c>{Route}/{facet}</c>. Adapters are not a builder input in v1, so this asserts the by-construction
/// guarantee that no <c>Adapter_Endpoint</c> is documented (R12.1).
/// </summary>
/// <remarks>
/// <see cref="VistaOpenApiDocumentBuilder.Build"/> is <c>[RequiresUnreferencedCode]</c> because it collects
/// per-view DTO schemas by reflecting over the row/write CLR types. Adapter absence is purely structural,
/// but building the whole document drives that reflection branch, so the trim warning is suppressed at the
/// class level, matching the sibling emitter property suites.
/// </remarks>
[SuppressMessage(
    "Trimming",
    "IL2026:Members annotated with RequiresUnreferencedCodeAttribute may break when trimming",
    Justification = "The property builds the full document, which drives the RUC per-view DTO schema reflection by design; trimming is not used for tests.")]
public sealed class AdapterEndpointAbsencePropertyTests
{
    /// <summary>Minimum generated cases required for the property (design Testing Strategy: ≥100).</summary>
    private const int Iterations = 100;

    /// <summary>
    /// The seven core facet suffixes the emitter may ever produce as a path's last segment. Any other
    /// suffix (a grid-adapter <c>RouteSuffix</c> such as <c>datatable</c>/<c>querybuilder</c>) is an
    /// Adapter_Endpoint and violates R12.1.
    /// </summary>
    private static readonly HashSet<string> CoreFacetSuffixes = new(StringComparer.Ordinal)
    {
        "list", "detail", "metadata", "export", "create", "update", "delete",
    };

    // Feature: openapi-emitter, Property 10: Adapter endpoints are absent from the v1 document.
    //
    // For any set of registered views — including views flagged as having grid adapters registered — the
    // emitted document contains no operation whose path is an Adapter_Endpoint ({route}/{RouteSuffix});
    // every operation path ends in one of list/detail/metadata/export/create/update/delete and sits exactly
    // at a registered view's {Route}/{facet}. Adapters are not a builder input in v1, so this asserts the
    // by-construction guarantee (R12.1).
    //
    // Validates: Requirements 12.1
    [Test]
    public void Every_Operation_Is_A_Core_Facet_Never_An_Adapter_Endpoint()
    {
        RegistryGenerators.Registry().Sample(
            generated =>
            {
                var document = new VistaOpenApiDocumentBuilder(
                    generated.Registry,
                    EmitterFixtures.SeamOptions(),
                    new VistaEndpointOptions(),
                    new VistaOpenApiOptions(),
                    generated.WriteFacets).Build();

                // The registered view routes are the only legal path prefixes (one view = one endpoint
                // root, D101/D103). Any emitted path must be exactly one of these routes + "/" + a core
                // facet — nothing else.
                var routes = new HashSet<string>(
                    generated.Views.Select(v => v.Route), StringComparer.Ordinal);

                foreach (var (path, method) in OperationPaths(document))
                {
                    var suffix = PathSuffix(path);

                    // (1) The facet suffix must be one of the seven core facets — never an adapter suffix.
                    if (!CoreFacetSuffixes.Contains(suffix))
                    {
                        throw new Exception(
                            "An operation path ends in a non-core (adapter) facet suffix — an " +
                            "Adapter_Endpoint must never be emitted in v1 (R12.1).\n" +
                            Describe(generated) + "\n" +
                            $"  Offending operation: {method} {path}\n" +
                            $"  Offending suffix: '{suffix}' (allowed: " +
                            string.Join("/", CoreFacetSuffixes.OrderBy(x => x, StringComparer.Ordinal)) +
                            ")");
                    }

                    // (2) The path must be exactly a registered view's Route + "/" + the core facet — no
                    // orphan/adapter path with a core-looking suffix but a foreign prefix.
                    var route = RoutePrefix(path);
                    if (route is null || !routes.Contains(route))
                    {
                        throw new Exception(
                            "An operation path does not sit under any registered view's Route — no " +
                            "orphan/adapter path may escape the View_Operation_Set (R12.1).\n" +
                            Describe(generated) + "\n" +
                            $"  Offending operation: {method} {path}\n" +
                            $"  Derived route prefix: '{route ?? "(none)"}'\n" +
                            "  Registered routes: " +
                            string.Join(", ", routes.OrderBy(x => x, StringComparer.Ordinal)));
                    }
                }
            },
            iter: Iterations);
    }

    /// <summary>
    /// Enumerates every emitted operation as <c>(path, method)</c>: the <c>GET</c> per path whose
    /// <see cref="OpenApiPathItem.Get"/> is populated and the <c>POST</c> per path whose
    /// <see cref="OpenApiPathItem.Post"/> is populated.
    /// </summary>
    private static IEnumerable<(string Path, string Method)> OperationPaths(OpenApiDocument document)
    {
        if (document.Paths is null)
        {
            yield break;
        }

        foreach (var (path, item) in document.Paths)
        {
            if (item.Get is not null)
            {
                yield return (path, "GET");
            }

            if (item.Post is not null)
            {
                yield return (path, "POST");
            }
        }
    }

    /// <summary>The facet token = the last path segment (for example <c>{Route}/list</c> → <c>list</c>).</summary>
    private static string PathSuffix(string path)
    {
        var index = path.LastIndexOf('/');
        return index < 0 ? path : path[(index + 1)..];
    }

    /// <summary>
    /// The route prefix = everything before the last path segment (for example <c>{Route}/list</c> →
    /// <c>{Route}</c>). Returns <see langword="null"/> when the path has no <c>/</c> separator.
    /// </summary>
    private static string? RoutePrefix(string path)
    {
        var index = path.LastIndexOf('/');
        return index <= 0 ? null : path[..index];
    }

    /// <summary>
    /// A compact rendering of the generated views and — crucially — the adapter-FLAGGED view names, so a
    /// failure message documents that even adapter-flagged views produced only core facets (the marker is a
    /// no-op by construction; see the file header).
    /// </summary>
    private static string Describe(GeneratedRegistry generated)
    {
        var views = string.Join(", ", generated.Views.Select(v => $"{v.Name}[{(v.IsReadOnly ? "ro" : "rw")}]"));
        var adapters = generated.AdapterViewNames.Count == 0
            ? "(none)"
            : string.Join(", ", generated.AdapterViewNames.OrderBy(x => x, StringComparer.Ordinal));
        return
            $"  Views ({generated.Views.Count}): {views}\n" +
            $"  Adapter-flagged views: {adapters}";
    }
}
