// Licensed to the a2n.Vista project. Published artifact — English only.
//
// The determinism / order-independence property test for the OpenAPI emitter (spec openapi-emitter,
// task 9.3; Property 7). Because the emitter is a SERIALIZER of an OpenAPI object model (not a parser),
// determinism plays the stabilizing role a round-trip plays for parsers: the emitted document JSON must be
// byte-for-byte stable across repeated builds and INDEPENDENT of the order in which the views were
// registered (and hence of any hash-set enumeration order).
//
// Two facets, over any generated registry:
//   (a) R9.1 — building twice over the SAME registry instance + seam configuration yields byte-identical
//       JSON (idempotence of the build).
//   (b) R9.2 — building over a NEW registry populated with the SAME views in a RANDOM PERMUTATION (and,
//       independently, in REVERSED registration order), reusing the same write-facet registry, yields JSON
//       byte-identical to the original build (registration/enumeration-order independence).
//
// The permutation is drawn deterministically WITHIN the CsCheck sample by composing the registry generator
// with a Fisher–Yates permutation generator keyed off generated swap indices, so a shrinking counterexample
// carries both the registry AND the exact permutation that broke determinism. The reversed order is always
// exercised alongside the random permutation for a cheap, adversarial ordering.
//
// The write-facet registry is reused verbatim across all builds: a view's concurrency token is keyed by
// view name (order-independent), so rebuilding the registry from a permutation of the same views leaves the
// token wiring unchanged and keeps the comparison honest.

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using a2n.Vista.AspNetCore.Configuration;
using a2n.Vista.Metadata;
using a2n.Vista.OpenApi;
using a2n.Vista.Ports;
using a2n.Vista.Write;
using CsCheck;
using TUnit.Core;

namespace a2n.Vista.Tests;

/// <summary>
/// Property-based test for deterministic, order-independent output — Property 7 of the OpenAPI emitter
/// (spec openapi-emitter, task 9.3; Requirements 9.1, 9.2). Over random registries generated by
/// <see cref="RegistryGenerators.Registry(int, int)"/> — each paired with a randomly generated permutation
/// of its registration order — it asserts that (a) two builds over the same registry produce byte-identical
/// document JSON and (b) rebuilding the registry from a permuted (and reversed) registration order of the
/// same views produces JSON byte-identical to the original.
/// </summary>
/// <remarks>
/// <see cref="VistaOpenApiDocumentBuilder.BuildJson"/> is <c>[RequiresUnreferencedCode]</c> because building
/// the full document drives the per-view DTO schema reflection branch. Determinism is a property of the
/// serialized bytes, but producing them exercises that branch, so the trim warning is suppressed at the
/// class level, matching the sibling emitter property suites; trimming is not used for tests.
/// </remarks>
[SuppressMessage(
    "Trimming",
    "IL2026:Members annotated with RequiresUnreferencedCodeAttribute may break when trimming",
    Justification = "The property builds the full document, which drives the RUC per-view DTO schema reflection by design; trimming is not used for tests.")]
public sealed class DeterminismPropertyTests
{
    /// <summary>Minimum generated cases required for the property (design Testing Strategy: ≥100).</summary>
    private const int Iterations = 100;

    // Feature: openapi-emitter, Property 7: Deterministic, order-independent output.
    //
    // For any set of registered views, two builds over the same registry and seam configuration produce
    // byte-for-byte identical document JSON; and for any permutation of the registration order of the same
    // views, the emitted JSON is byte-for-byte identical (ordering independent of registration and
    // enumeration order).
    //
    // Validates: Requirements 9.1, 9.2
    [Test]
    public void Document_Json_Is_Deterministic_And_Registration_Order_Independent()
    {
        Registries().Sample(
            testCase =>
            {
                var (generated, permutation) = testCase;

                // The same configuration for every build so only the registry (and its ordering) varies.
                static VistaOpenApiDocumentBuilder Builder(IViewRegistry registry, WriteFacetRegistry writeFacets) =>
                    new(
                        registry,
                        EmitterFixtures.SeamOptions(),
                        new VistaEndpointOptions(),
                        new VistaOpenApiOptions(),
                        writeFacets);

                // (a) R9.1 — idempotence: two builds over the SAME registry instance are byte-identical.
                var baseline = Builder(generated.Registry, generated.WriteFacets).BuildJson();
                var repeat = Builder(generated.Registry, generated.WriteFacets).BuildJson();
                AssertByteEqual(baseline, repeat, generated, "repeat build over the same registry (R9.1)");

                // (b) R9.2 — registration/enumeration-order independence: rebuild the registry from a
                // RANDOM PERMUTATION of the same views and assert byte-equality with the baseline.
                var permutedRegistry = RegistryFrom(generated.Views, permutation);
                var permuted = Builder(permutedRegistry, generated.WriteFacets).BuildJson();
                AssertByteEqual(baseline, permuted, generated, "build over a random permutation of registration order (R9.2)");

                // (b') R9.2 — a cheap adversarial ordering: reversed registration order.
                var reversedRegistry = RegistryFrom(generated.Views, ReverseIndices(generated.Views.Count));
                var reversed = Builder(reversedRegistry, generated.WriteFacets).BuildJson();
                AssertByteEqual(baseline, reversed, generated, "build over reversed registration order (R9.2)");
            },
            iter: Iterations);
    }

    /// <summary>
    /// Composes the registry generator with a permutation generator keyed off its view count, so each
    /// generated case carries both the registry and the exact permutation of its registration order to
    /// exercise (a shrinking counterexample thus pins down the offending ordering).
    /// </summary>
    private static Gen<(GeneratedRegistry Generated, int[] Permutation)> Registries() =>
        from generated in RegistryGenerators.Registry()
        from permutation in GenPermutation(generated.Views.Count)
        select (generated, permutation);

    /// <summary>
    /// A generator of a random permutation of the indices <c>0..n-1</c>, produced by a Fisher–Yates shuffle
    /// driven by <paramref name="n"/> generated swap indices (so the permutation shrinks with its seeds).
    /// </summary>
    /// <param name="n">The number of elements to permute (the generated view count, ≥1).</param>
    /// <returns>A generator of an <c>int[]</c> that is a permutation of <c>0..n-1</c>.</returns>
    private static Gen<int[]> GenPermutation(int n) =>
        Gen.Int[0, int.MaxValue].Array[n].Select(seeds =>
        {
            var permutation = new int[n];
            for (var i = 0; i < n; i++)
            {
                permutation[i] = i;
            }

            // Fisher–Yates: for i from n-1 down to 1, swap element i with a lower-or-equal index j derived
            // deterministically from the generated seed.
            for (var i = n - 1; i > 0; i--)
            {
                var j = seeds[i] % (i + 1);
                (permutation[i], permutation[j]) = (permutation[j], permutation[i]);
            }

            return permutation;
        });

    /// <summary>The reversed index sequence <c>n-1 .. 0</c> — a deterministic adversarial ordering.</summary>
    private static int[] ReverseIndices(int n)
    {
        var indices = new int[n];
        for (var i = 0; i < n; i++)
        {
            indices[i] = n - 1 - i;
        }

        return indices;
    }

    /// <summary>
    /// Builds a fresh <see cref="ViewRegistry"/> by adding <paramref name="views"/> in the order given by
    /// <paramref name="order"/> (a permutation of <c>0..views.Count-1</c>). View names are globally unique
    /// (D101/D103), so any registration order is valid and <see cref="ViewRegistry.Add"/> never collides.
    /// </summary>
    private static IViewRegistry RegistryFrom(IReadOnlyList<ViewMetadata> views, int[] order)
    {
        var registry = new ViewRegistry();
        foreach (var index in order)
        {
            registry.Add(views[index]);
        }

        return registry;
    }

    /// <summary>
    /// Asserts <paramref name="actual"/> is byte-for-byte identical to <paramref name="expected"/>. On a
    /// mismatch, throws an exception naming the first differing offset and a snippet of both documents
    /// around it, so CsCheck reports and shrinks a meaningful counterexample.
    /// </summary>
    private static void AssertByteEqual(string expected, string actual, GeneratedRegistry generated, string label)
    {
        if (string.Equals(expected, actual, StringComparison.Ordinal))
        {
            return;
        }

        var offset = FirstDifference(expected, actual);
        var views = string.Join(
            ", ",
            Describe(generated.Views));

        throw new Exception(
            "Determinism violated: the emitted document JSON differed on the " + label + ".\n" +
            $"  Views ({generated.Views.Count}): {views}\n" +
            $"  First difference at offset {offset} (expected length {expected.Length}, actual length {actual.Length}).\n" +
            $"  Expected: …{Snippet(expected, offset)}…\n" +
            $"  Actual:   …{Snippet(actual, offset)}…");
    }

    /// <summary>The index of the first character at which the two strings differ (or the shorter length).</summary>
    private static int FirstDifference(string a, string b)
    {
        var min = Math.Min(a.Length, b.Length);
        for (var i = 0; i < min; i++)
        {
            if (a[i] != b[i])
            {
                return i;
            }
        }

        return min;
    }

    /// <summary>A short, safely-clamped window of <paramref name="text"/> centered on <paramref name="offset"/>.</summary>
    private static string Snippet(string text, int offset)
    {
        const int window = 40;
        var start = Math.Max(0, offset - window / 2);
        var length = Math.Min(window, text.Length - start);
        return length <= 0 ? string.Empty : text.Substring(start, length);
    }

    /// <summary>Compact per-view descriptors (name + read/write posture) for counterexample messages.</summary>
    private static IEnumerable<string> Describe(IReadOnlyList<ViewMetadata> views)
    {
        foreach (var view in views)
        {
            yield return $"{view.Name}[{(view.IsReadOnly ? "ro" : "rw")}]";
        }
    }
}
