// Licensed to the a2n.Vista project. Published artifact — English only.
//
// The master endpoint-parity property test for the OpenAPI emitter (spec openapi-emitter, task 8.2;
// Property 1). The live route table (IViewRegistry) is the oracle: for ANY generated registry, the set of
// (method, path) operations in the emitted OpenApiDocument must equal EXACTLY the union over every view of
// its View_Operation_Set — {POST list, POST detail, GET metadata, POST export} for every view, plus
// {POST create, POST update, POST delete} for every writable view — each path prefixed by the view's
// ViewMetadata.Route. This is completeness (every expected operation present) AND soundness (no phantom
// operation), and it proves read-only views contribute no write operation while writable views contribute
// all seven facets.
//
// The expected set is computed straight from the same fixed facet table the surface documents
// (FacetOperations.ForView), so a divergence between the builder's emitted paths and the canonical facet
// set is what the property catches — not a re-statement of the builder's own internal wiring.

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using a2n.Vista.AspNetCore.Configuration;
using a2n.Vista.Metadata;
using a2n.Vista.OpenApi;
using a2n.Vista.OpenApi.Model;
using CsCheck;
using TUnit.Core;

namespace a2n.Vista.Tests;

/// <summary>
/// Property-based test for endpoint parity — Property 1 of the OpenAPI emitter (spec openapi-emitter,
/// task 8.2; Requirements 1.1, 1.2, 1.3, 1.4, 2.1, 2.2). Over random registries generated by
/// <see cref="RegistryGenerators.Registry(int, int)"/>, it builds the document and asserts the set of
/// emitted <c>(method, path)</c> operations equals exactly the union of every registered view's
/// <c>View_Operation_Set</c> (completeness ∧ soundness).
/// </summary>
/// <remarks>
/// <see cref="VistaOpenApiDocumentBuilder.Build"/> is <c>[RequiresUnreferencedCode]</c> because it collects
/// per-view DTO schemas by reflecting over the row/write CLR types. Endpoint parity is purely structural
/// (paths/methods), but building the whole document drives that reflection branch, so the trim warning is
/// suppressed at the class level, matching the sibling emitter/oracle property suites.
/// </remarks>
[SuppressMessage(
    "Trimming",
    "IL2026:Members annotated with RequiresUnreferencedCodeAttribute may break when trimming",
    Justification = "The property builds the full document, which drives the RUC per-view DTO schema reflection by design; trimming is not used for tests.")]
public sealed class EndpointParityPropertyTests
{
    /// <summary>Minimum generated cases required for the property (design Testing Strategy: ≥100).</summary>
    private const int Iterations = 100;

    // Feature: openapi-emitter, Property 1: Endpoint parity — the document's operations equal the live
    // View_Operation_Set.
    //
    // For any set of registered views, the set of (method, path) operations in the emitted OpenApiDocument
    // equals exactly the union over every view of its View_Operation_Set — {POST list, POST detail,
    // GET metadata, POST export} for every view plus {POST create, POST update, POST delete} for every
    // writable view — each path prefixed by that view's ViewMetadata.Route; there is no phantom operation
    // and read-only views contribute no write operation.
    //
    // Validates: Requirements 1.1, 1.2, 1.3, 1.4, 2.1, 2.2
    [Test]
    public void Document_Operations_Equal_The_Live_View_Operation_Set()
    {
        RegistryGenerators.Registry().Sample(
            generated =>
            {
                var document = new VistaOpenApiDocumentBuilder(
                    generated.Registry,
                    EmitterFixtures.SeamOptions(),
                    new VistaEndpointOptions(),
                    new VistaOpenApiOptions(),
                    generated.WriteFacets).Build();

                var actual = ActualOperations(document);
                var expected = ExpectedOperations(generated.Views);

                if (!actual.SetEquals(expected))
                {
                    var missing = expected.Except(actual).OrderBy(x => x, StringComparer.Ordinal).ToArray();
                    var phantom = actual.Except(expected).OrderBy(x => x, StringComparer.Ordinal).ToArray();

                    throw new Exception(
                        "Endpoint parity violated between the emitted document and the live " +
                        "View_Operation_Set.\n" +
                        $"  Views ({generated.Views.Count}): " +
                        string.Join(", ", generated.Views.Select(v => $"{v.Name}[{(v.IsReadOnly ? "ro" : "rw")}]")) +
                        "\n" +
                        $"  Missing (expected, not emitted) [{missing.Length}]: " +
                        (missing.Length == 0 ? "(none)" : string.Join(", ", missing)) + "\n" +
                        $"  Phantom (emitted, not expected) [{phantom.Length}]: " +
                        (phantom.Length == 0 ? "(none)" : string.Join(", ", phantom)));
                }
            },
            iter: Iterations);
    }

    /// <summary>
    /// The actual set of <c>(method, path)</c> operations the document emits: a <c>GET</c> entry per path
    /// whose <see cref="OpenApiPathItem.Get"/> is populated and a <c>POST</c> entry per path whose
    /// <see cref="OpenApiPathItem.Post"/> is populated.
    /// </summary>
    private static HashSet<string> ActualOperations(OpenApiDocument document)
    {
        var operations = new HashSet<string>(StringComparer.Ordinal);
        if (document.Paths is null)
        {
            return operations;
        }

        foreach (var (path, item) in document.Paths)
        {
            if (item.Get is not null)
            {
                operations.Add(Key("GET", path));
            }

            if (item.Post is not null)
            {
                operations.Add(Key("POST", path));
            }
        }

        return operations;
    }

    /// <summary>
    /// The expected set of <c>(method, path)</c> operations = the union over every view of its
    /// <c>View_Operation_Set</c>, computed from the canonical facet table
    /// (<see cref="FacetOperations.ForView(bool)"/>): <c>path = Route.TrimEnd('/') + "/" + PathSuffix</c>.
    /// </summary>
    private static HashSet<string> ExpectedOperations(IReadOnlyList<ViewMetadata> views)
    {
        var operations = new HashSet<string>(StringComparer.Ordinal);
        foreach (var view in views)
        {
            var route = view.Route.TrimEnd('/');
            foreach (var facet in FacetOperations.ForView(view.IsReadOnly))
            {
                operations.Add(Key(facet.HttpMethod, route + "/" + facet.PathSuffix));
            }
        }

        return operations;
    }

    /// <summary>Canonical <c>(method, path)</c> key for set comparison.</summary>
    private static string Key(string method, string path) => method + " " + path;
}
