// Licensed to the a2n.Vista project. Published artifact — English only.
//
// The error-response property test for the OpenAPI emitter (spec openapi-emitter, task 9.5; Property 9).
// The live route table (IViewRegistry) + the fixed facet table are the oracle: for ANY generated registry
// the emitted document must document the RFC 7807 error surface per facet:
//
//   * every body operation (list/detail/export/create/update/delete) documents a 400 (R6.2), and the
//     metadata GET — which carries no body — documents none;
//   * every operation documents a 403 when the app is NOT anonymous (R6.3), and NONE does when anonymous
//     (403 is gated on the not-anonymous posture — the error-side complement of Property 8);
//   * every documented error response (any of 400/403/404/409/428) uses the media type
//     application/problem+json and references the single, once-registered ProblemDetails schema (R6.5).
//
// Facets are identified structurally from the last path segment (the PathSuffix the builder emits), so the
// property checks the real emitted paths rather than re-stating the builder's internal wiring. The writable
// views come with generated.WriteFacets so token-bearing writable views (which additionally document
// 428/409 on update/delete) are covered — those extra error responses must equally be problem+json /
// ProblemDetails.
//
// Build() is [RequiresUnreferencedCode] because it collects per-view DTO schemas by reflecting over the
// row/write CLR types; the error surface is purely structural, but building the whole document drives that
// reflection branch, so the trim warning is suppressed at the class level (matching the sibling suites).

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using a2n.Vista.AspNetCore.Configuration;
using a2n.Vista.OpenApi;
using a2n.Vista.OpenApi.Model;
using CsCheck;
using TUnit.Core;

namespace a2n.Vista.Tests;

/// <summary>
/// Property-based test for the per-facet RFC 7807 error surface — Property 9 of the OpenAPI emitter (spec
/// openapi-emitter, task 9.5; Requirements 6.2, 6.3, 6.5). Over random registries generated by
/// <see cref="RegistryGenerators.Registry(int, int)"/>, it builds the document and asserts that every body
/// operation documents a <c>400</c>, every operation documents a <c>403</c> when not anonymous (and none
/// when anonymous), and every documented error response uses <c>application/problem+json</c> referencing
/// the single <c>ProblemDetails</c> schema.
/// </summary>
/// <remarks>
/// <see cref="VistaOpenApiDocumentBuilder.Build"/> is <c>[RequiresUnreferencedCode]</c> because it collects
/// per-view DTO schemas by reflecting over the row/write CLR types. The error surface is purely structural,
/// but building the whole document drives that reflection branch, so the trim warning is suppressed at the
/// class level, matching the sibling emitter property suites.
/// </remarks>
[SuppressMessage(
    "Trimming",
    "IL2026:Members annotated with RequiresUnreferencedCodeAttribute may break when trimming",
    Justification = "The property builds the full document, which drives the RUC per-view DTO schema reflection by design; trimming is not used for tests.")]
public sealed class ErrorResponsePropertyTests
{
    /// <summary>Minimum generated cases required for the property (design Testing Strategy: ≥100).</summary>
    private const int Iterations = 100;

    /// <summary>The path suffixes of the body-bearing facets that must document a <c>400</c> (R6.2).</summary>
    private static readonly HashSet<string> BodyFacetSuffixes = new(StringComparer.Ordinal)
    {
        "list", "detail", "export", "create", "update", "delete",
    };

    /// <summary>Every documented error status code the media-type/reference invariant applies to (R6.5).</summary>
    private static readonly string[] ErrorCodes = { "400", "403", "404", "409", "428" };

    /// <summary>The single shared RFC 7807 schema every error response must reference (R6.1/R6.5).</summary>
    private const string ProblemDetailsRef = "#/components/schemas/ProblemDetails";

    // Feature: openapi-emitter, Property 9: Error responses are documented per facet with the problem+json
    // shape.
    //
    // For any set of registered views, every list/detail/export/create/update/delete operation documents a
    // 400 response, every operation documents a 403 when the app is not anonymous, and every documented
    // error response uses the media type application/problem+json referencing the single ProblemDetails
    // schema.
    //
    // Validates: Requirements 6.2, 6.3, 6.5
    [Test]
    public void NotAnonymous_Documents_400_Per_Body_Facet_403_Everywhere_And_ProblemJson_Errors()
    {
        RegistryGenerators.Registry().Sample(
            generated =>
            {
                var document = new VistaOpenApiDocumentBuilder(
                    generated.Registry,
                    EmitterFixtures.SeamOptions(),
                    new VistaEndpointOptions(),
                    new VistaOpenApiOptions(),
                    generated.WriteFacets).Build();

                foreach (var (path, method, operation) in Operations(document))
                {
                    var suffix = PathSuffix(path);
                    var isBodyFacet = BodyFacetSuffixes.Contains(suffix);
                    var has400 = operation.Responses is not null && operation.Responses.ContainsKey("400");

                    // R6.2: body operations document a 400; the body-less metadata GET does not.
                    if (isBodyFacet && !has400)
                    {
                        throw new Exception(
                            $"Body operation '{method} {path}' (facet '{suffix}') is missing the expected " +
                            "'400' response (R6.2).");
                    }

                    if (!isBodyFacet && has400)
                    {
                        throw new Exception(
                            $"Non-body operation '{method} {path}' (facet '{suffix}') documents an " +
                            "unexpected '400' response (R6.2 — only body facets carry 400).");
                    }

                    // R6.3: not anonymous → every operation documents a 403.
                    if (operation.Responses is null || !operation.Responses.ContainsKey("403"))
                    {
                        throw new Exception(
                            $"Operation '{method} {path}' (facet '{suffix}') is missing the expected '403' " +
                            "response, but the app is not anonymous (R6.3).");
                    }

                    // R6.5: every documented error response is application/problem+json → ProblemDetails.
                    AssertErrorResponsesAreProblemJson(method, path, suffix, operation);
                }

                // R6.1/R6.5: the ProblemDetails schema is registered exactly once as a shared component.
                if (document.Components?.Schemas is null ||
                    !document.Components.Schemas.ContainsKey("ProblemDetails"))
                {
                    throw new Exception(
                        "The document does not register the shared 'ProblemDetails' schema under " +
                        "components.schemas (R6.1/R6.5). Views: " +
                        string.Join(", ", generated.Views.Select(v => v.Name)));
                }
            },
            iter: Iterations);
    }

    // Feature: openapi-emitter, Property 9: Error responses are documented per facet with the problem+json
    // shape (anonymous complement).
    //
    // For any set of registered views, when the app is anonymous no operation documents a 403 (the 403 is
    // gated on the not-anonymous posture); any other documented error response still uses
    // application/problem+json referencing the single ProblemDetails schema.
    //
    // Validates: Requirements 6.2, 6.3, 6.5
    [Test]
    public void Anonymous_Documents_No_403_And_Still_Uses_ProblemJson_Errors()
    {
        RegistryGenerators.Registry().Sample(
            generated =>
            {
                var document = new VistaOpenApiDocumentBuilder(
                    generated.Registry,
                    EmitterFixtures.SeamOptions(),
                    new VistaEndpointOptions { AllowAnonymous = true },
                    new VistaOpenApiOptions(),
                    generated.WriteFacets).Build();

                foreach (var (path, method, operation) in Operations(document))
                {
                    var suffix = PathSuffix(path);

                    // R6.3: anonymous → no operation documents a 403.
                    if (operation.Responses is not null && operation.Responses.ContainsKey("403"))
                    {
                        throw new Exception(
                            $"Operation '{method} {path}' (facet '{suffix}') documents a '403' response, but " +
                            "the app is anonymous, so 403 must not be present (R6.3).");
                    }

                    // R6.5: the remaining error responses (400/404/409/428) are still problem+json.
                    AssertErrorResponsesAreProblemJson(method, path, suffix, operation);
                }
            },
            iter: Iterations);
    }

    /// <summary>
    /// Asserts that every documented error response of <paramref name="operation"/> (any status code in
    /// <see cref="ErrorCodes"/>) uses the media type <c>application/problem+json</c> and references the
    /// single <c>ProblemDetails</c> schema by <c>$ref</c> (R6.5). Throws a descriptive message so CsCheck
    /// can shrink to the offending operation/code.
    /// </summary>
    private static void AssertErrorResponsesAreProblemJson(
        string method,
        string path,
        string suffix,
        OpenApiOperation operation)
    {
        if (operation.Responses is null)
        {
            return;
        }

        foreach (var code in ErrorCodes)
        {
            if (!operation.Responses.TryGetValue(code, out var response))
            {
                continue;
            }

            var content = response.Content;
            if (content is null || !content.TryGetValue("application/problem+json", out var mediaType))
            {
                throw new Exception(
                    $"Error response '{code}' on '{method} {path}' (facet '{suffix}') does not use the " +
                    "media type 'application/problem+json' (R6.5). Media types present: " +
                    (content is null ? "(none)" : string.Join(", ", content.Keys)) + ".");
            }

            var actualRef = mediaType.Schema?.Ref;
            if (!string.Equals(actualRef, ProblemDetailsRef, StringComparison.Ordinal))
            {
                throw new Exception(
                    $"Error response '{code}' on '{method} {path}' (facet '{suffix}') references schema " +
                    $"'{actualRef ?? "(null)"}' for application/problem+json, expected '{ProblemDetailsRef}' " +
                    "(R6.5).");
            }
        }
    }

    /// <summary>
    /// Enumerates every emitted operation as <c>(path, method, operation)</c>: the <c>GET</c> per path whose
    /// <see cref="OpenApiPathItem.Get"/> is populated and the <c>POST</c> per path whose
    /// <see cref="OpenApiPathItem.Post"/> is populated.
    /// </summary>
    private static IEnumerable<(string Path, string Method, OpenApiOperation Operation)> Operations(
        OpenApiDocument document)
    {
        if (document.Paths is null)
        {
            yield break;
        }

        foreach (var (path, item) in document.Paths)
        {
            if (item.Get is not null)
            {
                yield return (path, "GET", item.Get);
            }

            if (item.Post is not null)
            {
                yield return (path, "POST", item.Post);
            }
        }
    }

    /// <summary>The facet token = the last path segment (for example <c>{Route}/list</c> → <c>list</c>).</summary>
    private static string PathSuffix(string path)
    {
        var index = path.LastIndexOf('/');
        return index < 0 ? path : path[(index + 1)..];
    }
}
