// Licensed to the a2n.Vista project. Published artifact — English only.
//
// OpenAPI emitter VALIDITY property test (spec openapi-emitter, task 9.2).
//
// Property 6: The document is a valid OpenAPI 3.x document.
//   For any set of registered views, the emitted document parses without structural error under a
//   conformant OpenAPI 3.x validator, declares a supported 3.x version, and carries a populated `info`
//   with a title and a version.
//
// Validates: Requirements 8.1, 8.2.
//
// Oracle: a conformant OpenAPI 3.x validator applied to the emitted JSON. Validator choice — a FOCUSED,
// self-contained structural validator over the parsed System.Text.Json JsonDocument of BuildJson(), rather
// than a Microsoft.OpenApi reader dependency. Rationale: the emitter multi-targets net8.0/net9.0/net10.0;
// Microsoft.OpenApi is absent on net8.0 (it only arrives transitively via Microsoft.AspNetCore.OpenApi,
// net9+), and net9 pulls Microsoft.OpenApi 1.6.x while net10 pulls the incompatible 2.x reader API. A
// single pinned reader version would risk downgrading the emitter's own transitive 2.x on net10 and would
// still require per-TFM #if for the 1.x/2.x API split. The structural validator below is TFM-agnostic,
// needs no package changes, and directly encodes the OpenAPI 3.x structural rules the emitter must satisfy
// (openapi 3.x; populated info; paths object; every operation has an operationId + a non-empty responses
// map where each response has a description; components.schemas is an object; every $ref resolves to a
// present component schema; requestBody/response media types carry a schema; securitySchemes are typed).
//
// CsCheck-via-TUnit idiom: RegistryGenerators.Registry().Sample(action, iter: 100) at >=100 iterations,
// matching the sibling structural suites. BuildJson() is [RequiresUnreferencedCode] (per-view DTO schema
// generation reflects over CLR row/CRUD types, D96 asymmetry), so the trim warning is suppressed at the
// class level — the property builds the whole document by design.

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using a2n.Vista.AspNetCore.Configuration;
using a2n.Vista.OpenApi;
using CsCheck;
using TUnit.Core;

namespace a2n.Vista.Tests;

/// <summary>
/// Property 6 (task 9.2): the emitted document is a valid OpenAPI 3.x document. Over random registries
/// generated by <see cref="RegistryGenerators.Registry(int, int)"/>, it serializes the document to JSON,
/// parses it, and runs it through a focused conformant OpenAPI 3.x structural validator, asserting no
/// structural errors, a supported <c>3.x</c> version, and a populated <c>info</c> with a non-empty title
/// and version (Requirements 8.1, 8.2).
/// </summary>
/// <remarks>
/// <see cref="VistaOpenApiDocumentBuilder.BuildJson"/> is <c>[RequiresUnreferencedCode]</c> because it
/// builds the full document, which collects per-view DTO schemas by reflecting over the row/write CLR types
/// (D96 asymmetry). Validity is structural, but building the whole document drives that reflection branch,
/// so the trim warning is suppressed at the class level, matching the sibling emitter property suites.
/// </remarks>
[SuppressMessage(
    "Trimming",
    "IL2026:Members annotated with RequiresUnreferencedCodeAttribute may break when trimming",
    Justification = "The property builds the full document, which drives the RUC per-view DTO schema reflection by design; trimming is not used for tests.")]
public sealed class OpenApiValidityPropertyTests
{
    /// <summary>Minimum generated cases required for the property (design Testing Strategy: >=100).</summary>
    private const int Iterations = 100;

    // Feature: openapi-emitter, Property 6: The document is a valid OpenAPI 3.x document.
    //
    // For any set of registered views, the emitted document parses without structural error under a
    // conformant OpenAPI 3.x validator, declares a supported 3.x version, and carries a populated `info`
    // with a title and a version.
    //
    // Validates: Requirements 8.1, 8.2
    [Test]
    public void Emitted_Document_Is_A_Valid_OpenApi_3x_Document()
    {
        RegistryGenerators.Registry().Sample(
            generated =>
            {
                var json = new VistaOpenApiDocumentBuilder(
                    generated.Registry,
                    EmitterFixtures.SeamOptions(),
                    new VistaEndpointOptions(),
                    new VistaOpenApiOptions(),
                    generated.WriteFacets).BuildJson();

                var errors = ValidateOpenApi3x(json);
                if (errors.Count > 0)
                {
                    throw new Exception(
                        "Emitted document is not a valid OpenAPI 3.x document " +
                        $"(views: {generated.Views.Count}).\n" +
                        "  Structural errors:\n    - " + string.Join("\n    - ", errors) + "\n" +
                        "  Document JSON:\n" + Snippet(json));
                }
            },
            iter: Iterations);
    }

    // ===== Focused, conformant OpenAPI 3.x structural validator =========================================

    /// <summary>
    /// Parses <paramref name="json"/> and checks the OpenAPI 3.x structural rules the emitter must satisfy,
    /// accumulating every violation. An empty result means the document is structurally valid.
    /// </summary>
    /// <param name="json">The emitted OpenAPI document JSON.</param>
    /// <returns>The list of structural errors (empty when valid).</returns>
    private static List<string> ValidateOpenApi3x(string json)
    {
        var errors = new List<string>();

        JsonDocument doc;
        try
        {
            doc = JsonDocument.Parse(json);
        }
        catch (JsonException ex)
        {
            return new List<string> { "Document is not well-formed JSON: " + ex.Message };
        }

        using (doc)
        {
            var root = doc.RootElement;
            if (root.ValueKind != JsonValueKind.Object)
            {
                errors.Add("Root is not a JSON object.");
                return errors;
            }

            // --- openapi: a supported 3.x version string (R8.1) ---------------------------------------
            if (!root.TryGetProperty("openapi", out var openapi) || openapi.ValueKind != JsonValueKind.String)
            {
                errors.Add("Missing or non-string 'openapi' version.");
            }
            else
            {
                var version = openapi.GetString();
                if (string.IsNullOrEmpty(version) || !version!.StartsWith("3.", StringComparison.Ordinal))
                {
                    errors.Add($"'openapi' version '{version}' is not a supported 3.x version.");
                }
            }

            // --- info: populated with a non-empty title and version (R8.1) ----------------------------
            if (!root.TryGetProperty("info", out var info) || info.ValueKind != JsonValueKind.Object)
            {
                errors.Add("Missing or non-object 'info'.");
            }
            else
            {
                RequireNonEmptyString(info, "title", "info.title", errors);
                RequireNonEmptyString(info, "version", "info.version", errors);
            }

            // --- collect the defined component schema names (for $ref resolution) ---------------------
            var definedSchemas = new HashSet<string>(StringComparer.Ordinal);
            if (root.TryGetProperty("components", out var components))
            {
                if (components.ValueKind != JsonValueKind.Object)
                {
                    errors.Add("'components' is present but is not an object.");
                }
                else
                {
                    if (components.TryGetProperty("schemas", out var schemas))
                    {
                        if (schemas.ValueKind != JsonValueKind.Object)
                        {
                            errors.Add("'components.schemas' is present but is not an object.");
                        }
                        else
                        {
                            foreach (var schema in schemas.EnumerateObject())
                            {
                                definedSchemas.Add(schema.Name);
                            }
                        }
                    }

                    ValidateSecuritySchemes(components, errors);
                }
            }

            // --- paths: an object; each operation is well-formed --------------------------------------
            if (!root.TryGetProperty("paths", out var paths) || paths.ValueKind != JsonValueKind.Object)
            {
                errors.Add("Missing or non-object 'paths'.");
            }
            else
            {
                foreach (var path in paths.EnumerateObject())
                {
                    if (path.Value.ValueKind != JsonValueKind.Object)
                    {
                        errors.Add($"Path item '{path.Name}' is not an object.");
                        continue;
                    }

                    foreach (var method in new[] { "get", "post" })
                    {
                        if (path.Value.TryGetProperty(method, out var operation))
                        {
                            ValidateOperation(path.Name, method, operation, errors);
                        }
                    }
                }
            }

            // --- referential integrity: every $ref resolves to a present component schema (R8.3-adjacent
            //     belt-and-suspenders; the validity property leans on it because a dangling $ref makes the
            //     document non-conformant) --------------------------------------------------------------
            foreach (var reference in CollectRefs(root))
            {
                const string prefix = "#/components/schemas/";
                if (!reference.StartsWith(prefix, StringComparison.Ordinal))
                {
                    errors.Add($"'$ref' '{reference}' does not target '#/components/schemas/<name>'.");
                    continue;
                }

                var name = reference.Substring(prefix.Length);
                if (name.Length == 0 || !definedSchemas.Contains(name))
                {
                    errors.Add($"Dangling '$ref' '{reference}' (no such component schema).");
                }
            }
        }

        return errors;
    }

    /// <summary>Validates a single operation: operationId, responses, request/response media schemas.</summary>
    private static void ValidateOperation(string path, string method, JsonElement operation, List<string> errors)
    {
        var where = $"{method.ToUpperInvariant()} {path}";

        if (operation.ValueKind != JsonValueKind.Object)
        {
            errors.Add($"Operation {where} is not an object.");
            return;
        }

        // Every operation has an operationId (R1.5 wiring; also a validity/interoperability requirement).
        RequireNonEmptyString(operation, "operationId", $"{where}.operationId", errors);

        // Responses: an object with at least one response, each with a description; media types carry a schema.
        if (!operation.TryGetProperty("responses", out var responses) || responses.ValueKind != JsonValueKind.Object)
        {
            errors.Add($"Operation {where} has a missing or non-object 'responses'.");
        }
        else
        {
            var responseCount = 0;
            foreach (var response in responses.EnumerateObject())
            {
                responseCount++;
                if (response.Value.ValueKind != JsonValueKind.Object)
                {
                    errors.Add($"Response {where} '{response.Name}' is not an object.");
                    continue;
                }

                RequireNonEmptyString(response.Value, "description", $"{where} '{response.Name}'.description", errors);
                ValidateContentSchemas(response.Value, $"{where} response '{response.Name}'", errors);
            }

            if (responseCount == 0)
            {
                errors.Add($"Operation {where} declares no responses.");
            }
        }

        // requestBody (when present): a content object whose media types each carry a schema.
        if (operation.TryGetProperty("requestBody", out var requestBody))
        {
            if (requestBody.ValueKind != JsonValueKind.Object)
            {
                errors.Add($"Operation {where} 'requestBody' is not an object.");
            }
            else if (!requestBody.TryGetProperty("content", out var content) || content.ValueKind != JsonValueKind.Object)
            {
                errors.Add($"Operation {where} 'requestBody' has a missing or non-object 'content'.");
            }
            else
            {
                ValidateContentSchemas(requestBody, $"{where} requestBody", errors);
            }
        }
    }

    /// <summary>Validates that every media type under a <c>content</c> map carries a schema object.</summary>
    private static void ValidateContentSchemas(JsonElement carrier, string where, List<string> errors)
    {
        if (!carrier.TryGetProperty("content", out var content) || content.ValueKind != JsonValueKind.Object)
        {
            return;
        }

        foreach (var media in content.EnumerateObject())
        {
            if (media.Value.ValueKind != JsonValueKind.Object)
            {
                errors.Add($"{where} media type '{media.Name}' is not an object.");
                continue;
            }

            if (!media.Value.TryGetProperty("schema", out var schema) || schema.ValueKind != JsonValueKind.Object)
            {
                errors.Add($"{where} media type '{media.Name}' has a missing or non-object 'schema'.");
            }
        }
    }

    /// <summary>Validates that each entry under <c>components.securitySchemes</c> is a typed object.</summary>
    private static void ValidateSecuritySchemes(JsonElement components, List<string> errors)
    {
        if (!components.TryGetProperty("securitySchemes", out var schemes))
        {
            return;
        }

        if (schemes.ValueKind != JsonValueKind.Object)
        {
            errors.Add("'components.securitySchemes' is present but is not an object.");
            return;
        }

        foreach (var scheme in schemes.EnumerateObject())
        {
            if (scheme.Value.ValueKind != JsonValueKind.Object)
            {
                errors.Add($"Security scheme '{scheme.Name}' is not an object.");
                continue;
            }

            RequireNonEmptyString(scheme.Value, "type", $"securityScheme '{scheme.Name}'.type", errors);
        }
    }

    /// <summary>Records an error when <paramref name="property"/> is absent, non-string, or empty.</summary>
    private static void RequireNonEmptyString(JsonElement owner, string property, string label, List<string> errors)
    {
        if (!owner.TryGetProperty(property, out var value) || value.ValueKind != JsonValueKind.String
            || string.IsNullOrEmpty(value.GetString()))
        {
            errors.Add($"Missing or empty '{label}'.");
        }
    }

    /// <summary>Recursively collects every <c>$ref</c> string value anywhere in the document.</summary>
    private static List<string> CollectRefs(JsonElement element)
    {
        var refs = new List<string>();
        Walk(element, refs);
        return refs;

        static void Walk(JsonElement node, List<string> acc)
        {
            switch (node.ValueKind)
            {
                case JsonValueKind.Object:
                    foreach (var property in node.EnumerateObject())
                    {
                        if (string.Equals(property.Name, "$ref", StringComparison.Ordinal)
                            && property.Value.ValueKind == JsonValueKind.String)
                        {
                            acc.Add(property.Value.GetString()!);
                        }
                        else
                        {
                            Walk(property.Value, acc);
                        }
                    }

                    break;

                case JsonValueKind.Array:
                    foreach (var item in node.EnumerateArray())
                    {
                        Walk(item, acc);
                    }

                    break;
            }
        }
    }

    /// <summary>Returns the JSON as-is when short, or a head/tail snippet for a compact failure message.</summary>
    private static string Snippet(string json)
    {
        const int max = 4000;
        if (json.Length <= max)
        {
            return json;
        }

        return json.Substring(0, max / 2) + "\n  ... [truncated] ...\n" + json.Substring(json.Length - (max / 2));
    }
}
