// Licensed to the a2n.Vista project. Published artifact — English only.
//
// The referential-integrity property test for the OpenAPI emitter (spec openapi-emitter, task 9.1;
// Property 5). The registry is the oracle: for ANY generated registry, the emitted OpenApiDocument must be
// internally self-consistent — every $ref must resolve to a schema actually present under
// components.schemas (no dangling reference, R8.3), and every shared schema (an envelope, FilterNode,
// ProblemDetails, or a per-view DTO) must be emitted ONCE under components.schemas and REFERENCED by
// operations rather than inlined (R3.6/R4.5).
//
// The "emitted once" half is partly structural: components.schemas is a name-keyed map, so a given name is
// inherently present at most once. The property therefore adds the operative half — that operations
// REFERENCE those shared schemas by $ref rather than duplicating their shape inline. Concretely, every
// request-body content schema and every JSON success/error response content schema (envelopes, DTOs,
// ProblemDetails) must be a $ref, never an inline object carrying its own Properties. (Bodyless success
// responses — the update/delete NoContentOr200 — carry no content and are trivially compliant; header
// schemas such as ETag/If-None-Match are inline scalars by design and are not shared-schema references.)
//
// On any violation the property throws a descriptive message (the dangling ref name, or the inlined body
// location) so CsCheck shrinks to a minimal counterexample.

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using a2n.Vista.AspNetCore.Configuration;
using a2n.Vista.OpenApi;
using a2n.Vista.OpenApi.Model;
using CsCheck;
using TUnit.Core;

namespace a2n.Vista.Tests;

/// <summary>
/// Property-based test for referential integrity — Property 5 of the OpenAPI emitter (spec openapi-emitter,
/// task 9.1; Requirements 3.6, 4.5, 8.3). Over random registries generated by
/// <see cref="RegistryGenerators.Registry(int, int)"/>, it builds the document and asserts that every
/// <c>$ref</c> resolves under <c>components.schemas</c> (no dangling reference) and that operations
/// reference shared schemas by <c>$ref</c> rather than inlining them (each shared schema is emitted once).
/// </summary>
/// <remarks>
/// <see cref="VistaOpenApiDocumentBuilder.Build"/> is <c>[RequiresUnreferencedCode]</c> because it collects
/// per-view DTO schemas by reflecting over the row/write CLR types. Referential integrity is purely
/// structural, but building the whole document drives that reflection branch, so the trim warning is
/// suppressed at the class level, matching the sibling emitter/oracle property suites.
/// </remarks>
[SuppressMessage(
    "Trimming",
    "IL2026:Members annotated with RequiresUnreferencedCodeAttribute may break when trimming",
    Justification = "The property builds the full document, which drives the RUC per-view DTO schema reflection by design; trimming is not used for tests.")]
public sealed class ReferentialIntegrityPropertyTests
{
    /// <summary>Minimum generated cases required for the property (design Testing Strategy: ≥100).</summary>
    private const int Iterations = 100;

    /// <summary>The OpenAPI local component-schema reference prefix.</summary>
    private const string SchemaRefPrefix = "#/components/schemas/";

    // Feature: openapi-emitter, Property 5: Referential integrity — every $ref resolves and shared schemas
    // are emitted once.
    //
    // For any set of registered views, every $ref in the document points to a schema present under
    // components.schemas (no dangling reference), and each shared schema (an envelope, FilterNode,
    // ProblemDetails, or a given DTO) appears exactly once in components.schemas and is referenced rather
    // than inlined by every operation that uses it.
    //
    // Validates: Requirements 3.6, 4.5, 8.3
    [Test]
    public void Every_Ref_Resolves_And_Shared_Schemas_Are_Referenced_Not_Inlined()
    {
        RegistryGenerators.Registry().Sample(
            generated =>
            {
                var document = new VistaOpenApiDocumentBuilder(
                    generated.Registry,
                    EmitterFixtures.SeamOptions(),
                    new VistaEndpointOptions(),
                    new VistaOpenApiOptions(),
                    generated.WriteFacets).Build();

                var componentNames = ComponentSchemaNames(document);

                // --- (1) No dangling reference (R8.3) --------------------------------------------------
                // Collect every $ref that appears anywhere in the document and require each local
                // component reference to resolve to a schema present under components.schemas.
                var references = new List<string>();
                CollectDocumentRefs(document, references);

                foreach (var reference in references)
                {
                    if (!reference.StartsWith(SchemaRefPrefix, StringComparison.Ordinal))
                    {
                        throw new Exception(
                            "A $ref does not target a local component schema (unexpected reference form).\n" +
                            DescribeViews(generated) + "\n" +
                            $"  Offending $ref: '{reference}'");
                    }

                    var name = reference[SchemaRefPrefix.Length..];
                    if (!componentNames.Contains(name))
                    {
                        throw new Exception(
                            "Dangling $ref: the reference points to a schema absent from components.schemas " +
                            "(referential integrity, R8.3).\n" +
                            DescribeViews(generated) + "\n" +
                            $"  Dangling $ref: '{reference}' (missing component '{name}')\n" +
                            "  Present components: " +
                            (componentNames.Count == 0
                                ? "(none)"
                                : string.Join(", ", componentNames.OrderBy(x => x, StringComparer.Ordinal))));
                    }
                }

                // --- (2) Shared schemas are referenced, not inlined (R3.6/R4.5) ------------------------
                // components.schemas is a name-keyed map, so each shared schema is inherently emitted once;
                // the operative half is that operations REFERENCE those schemas by $ref rather than
                // duplicating their shape inline. Every request-body content schema and every JSON
                // success/error response content schema must be a $ref (never an inline object).
                AssertBodiesAreReferences(document, generated);
            },
            iter: Iterations);
    }

    /// <summary>The set of component-schema names declared under <c>components.schemas</c>.</summary>
    private static HashSet<string> ComponentSchemaNames(OpenApiDocument document)
    {
        var names = new HashSet<string>(StringComparer.Ordinal);
        var schemas = document.Components?.Schemas;
        if (schemas is not null)
        {
            foreach (var name in schemas.Keys)
            {
                names.Add(name);
            }
        }

        return names;
    }

    /// <summary>
    /// Collects every <c>$ref</c> string appearing anywhere in the document: within each operation's
    /// parameter/request/response/header schemas and within every schema registered under
    /// <c>components.schemas</c> (recursively through <c>items</c>, <c>properties</c>, <c>oneOf</c>, and any
    /// discriminator mapping).
    /// </summary>
    private static void CollectDocumentRefs(OpenApiDocument document, List<string> references)
    {
        if (document.Paths is not null)
        {
            foreach (var item in document.Paths.Values)
            {
                CollectOperationRefs(item.Get, references);
                CollectOperationRefs(item.Post, references);
            }
        }

        var schemas = document.Components?.Schemas;
        if (schemas is not null)
        {
            foreach (var schema in schemas.Values)
            {
                CollectSchemaRefs(schema, references);
            }
        }
    }

    /// <summary>Collects the <c>$ref</c>s reachable from a single operation (may be <see langword="null"/>).</summary>
    private static void CollectOperationRefs(OpenApiOperation? operation, List<string> references)
    {
        if (operation is null)
        {
            return;
        }

        if (operation.Parameters is not null)
        {
            foreach (var parameter in operation.Parameters)
            {
                CollectSchemaRefs(parameter.Schema, references);
            }
        }

        if (operation.RequestBody?.Content is not null)
        {
            foreach (var media in operation.RequestBody.Content.Values)
            {
                CollectSchemaRefs(media.Schema, references);
            }
        }

        if (operation.Responses is not null)
        {
            foreach (var response in operation.Responses.Values)
            {
                if (response.Content is not null)
                {
                    foreach (var media in response.Content.Values)
                    {
                        CollectSchemaRefs(media.Schema, references);
                    }
                }

                if (response.Headers is not null)
                {
                    foreach (var header in response.Headers.Values)
                    {
                        CollectSchemaRefs(header.Schema, references);
                    }
                }
            }
        }
    }

    /// <summary>
    /// Recursively collects every <c>$ref</c> reachable from a schema: its own <see cref="OpenApiSchema.Ref"/>,
    /// its <see cref="OpenApiSchema.Items"/>, its <see cref="OpenApiSchema.Properties"/> values, its
    /// <see cref="OpenApiSchema.OneOf"/> variants, and any <see cref="OpenApiDiscriminator.Mapping"/> targets.
    /// </summary>
    private static void CollectSchemaRefs(OpenApiSchema? schema, List<string> references)
    {
        if (schema is null)
        {
            return;
        }

        if (schema.Ref is not null)
        {
            references.Add(schema.Ref);
        }

        CollectSchemaRefs(schema.Items, references);

        if (schema.Properties is not null)
        {
            foreach (var property in schema.Properties.Values)
            {
                CollectSchemaRefs(property, references);
            }
        }

        if (schema.OneOf is not null)
        {
            foreach (var variant in schema.OneOf)
            {
                CollectSchemaRefs(variant, references);
            }
        }

        if (schema.Discriminator?.Mapping is not null)
        {
            foreach (var target in schema.Discriminator.Mapping.Values)
            {
                references.Add(target);
            }
        }
    }

    /// <summary>
    /// Asserts that every request-body content schema and every response content schema across every
    /// operation is a <c>$ref</c> (a shared component reference) rather than an inline shape — the
    /// operative half of "shared schemas are emitted once and referenced, not inlined" (R3.6/R4.5). A body
    /// schema that carries its own <see cref="OpenApiSchema.Properties"/>/<see cref="OpenApiSchema.OneOf"/>
    /// instead of a <c>$ref</c> is an inlined duplication and fails the property.
    /// </summary>
    private static void AssertBodiesAreReferences(OpenApiDocument document, GeneratedRegistry generated)
    {
        if (document.Paths is null)
        {
            return;
        }

        foreach (var (path, item) in document.Paths)
        {
            AssertOperationBodiesAreReferences(path, "GET", item.Get, generated);
            AssertOperationBodiesAreReferences(path, "POST", item.Post, generated);
        }
    }

    private static void AssertOperationBodiesAreReferences(
        string path, string method, OpenApiOperation? operation, GeneratedRegistry generated)
    {
        if (operation is null)
        {
            return;
        }

        // The request body payload must be a reference to a shared component, never an inline object.
        if (operation.RequestBody?.Content is not null)
        {
            foreach (var (mediaType, media) in operation.RequestBody.Content)
            {
                AssertContentSchemaIsReference(
                    path, method, operation.OperationId, "request body", mediaType, media.Schema, generated);
            }
        }

        // Every response that carries content (JSON success bodies and problem+json error bodies) must
        // reference a shared component. A bodyless response (update/delete 200/204, metadata 304) carries
        // no content and is trivially compliant.
        if (operation.Responses is not null)
        {
            foreach (var (code, response) in operation.Responses)
            {
                if (response.Content is null)
                {
                    continue;
                }

                foreach (var (mediaType, media) in response.Content)
                {
                    AssertContentSchemaIsReference(
                        path, method, operation.OperationId, "response " + code, mediaType, media.Schema, generated);
                }
            }
        }
    }

    /// <summary>
    /// Asserts a single content schema is a <c>$ref</c>. Throws a descriptive message identifying the
    /// operation, the content slot, and the offending inline shape when it is not — so CsCheck shrinks to a
    /// minimal registry that inlines a body.
    /// </summary>
    private static void AssertContentSchemaIsReference(
        string path,
        string method,
        string? operationId,
        string slot,
        string mediaType,
        OpenApiSchema? schema,
        GeneratedRegistry generated)
    {
        if (schema is not null && schema.Ref is not null)
        {
            return;
        }

        var shape = schema is null
            ? "(missing schema)"
            : DescribeInlineShape(schema);

        throw new Exception(
            "A shared schema is inlined rather than referenced by $ref (referential integrity, " +
            "R3.6/R4.5).\n" +
            DescribeViews(generated) + "\n" +
            $"  Operation: {method} {path} (operationId '{operationId}')\n" +
            $"  Slot: {slot} content '{mediaType}'\n" +
            $"  Offending inline schema: {shape}");
    }

    /// <summary>A concise description of an inline (non-<c>$ref</c>) schema for a failure message.</summary>
    private static string DescribeInlineShape(OpenApiSchema schema)
    {
        var parts = new List<string>();
        if (schema.Type is not null)
        {
            parts.Add("type=" + schema.Type);
        }

        if (schema.Properties is not null)
        {
            parts.Add("properties=[" + string.Join(", ", schema.Properties.Keys) + "]");
        }

        if (schema.OneOf is not null)
        {
            parts.Add($"oneOf(count={schema.OneOf.Count})");
        }

        if (schema.Items is not null)
        {
            parts.Add("array-items");
        }

        return parts.Count == 0 ? "(empty/permissive object)" : string.Join(" ", parts);
    }

    /// <summary>A compact rendering of the generated views for failure diagnostics.</summary>
    private static string DescribeViews(GeneratedRegistry generated) =>
        $"  Views ({generated.Views.Count}): " +
        string.Join(", ", generated.Views.Select(v => $"{v.Name}[{(v.IsReadOnly ? "ro" : "rw")}]"));
}
