// Licensed to the a2n.Vista project. Published artifact — English only.
//
// Snapshot/golden tests for ViewAccessorGenerator (Phase 1, M9, D117; requirement R6.1). The generator
// is driven directly via CSharpGeneratorDriver over in-memory source (see GeneratorTestHarness). The
// tests cover the three representative shapes called out by task 4.1:
//   * a typed single-key view (class : View<TQuery>) — full golden of the generated accessor map +
//     [ModuleInitializer];
//   * a typed CRUD view (class : View<TQuery, TCrud>) — generated accessor map asserted;
//   * a NON-partial view — VISTA0001 (error) reported and no accessor source emitted for it.

using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using TUnit.Assertions;
using TUnit.Assertions.Extensions;
using TUnit.Core;

namespace a2n.Vista.SourceGenerators.Tests;

public sealed class ViewAccessorGeneratorTests
{
    // ---- typed single-key view: class XView : View<TQuery>, partial --------------------------------

    private const string SingleKeyViewSource = @"
namespace App
{
    public sealed class CustomerListItem
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
    }

    public partial class CustomerListView : a2n.Vista.Authoring.View<CustomerListItem>
    {
    }
}
";

    // Golden text for the single-key view. Generated source uses fixed "\n" line endings; the harness
    // normalizes to "\n" too. If the generator output legitimately changes, re-capture this from the
    // actual generated text (do NOT change the generator to match the golden).
    private const string SingleKeyGolden =
        "// <auto-generated/>\n" +
        "#nullable enable\n" +
        "\n" +
        "file static class CustomerListView_VistaAccessors\n" +
        "{\n" +
        "    public static readonly global::System.Collections.Generic.Dictionary<string, global::System.Func<object, object?>> Map = new()\n" +
        "    {\n" +
        "        [\"Id\"] = static row => ((global::App.CustomerListItem)row).Id,\n" +
        "        [\"Name\"] = static row => ((global::App.CustomerListItem)row).Name,\n" +
        "    };\n" +
        "\n" +
        "    [global::System.Runtime.CompilerServices.ModuleInitializer]\n" +
        "    internal static void Register()\n" +
        "        => global::a2n.Vista.Metadata.ViewAccessorRegistry.Register(\n" +
        "               new global::App.CustomerListView().Name, Map);\n" +
        "}\n";

    [Test]
    public async Task SingleKeyView_Emits_Golden_Accessor_Map_And_ModuleInitializer()
    {
        var result = GeneratorTestHarness.Run(SingleKeyViewSource);

        // No diagnostics for a well-formed partial view.
        await Assert.That(result.Diagnostics.Any(static d => d.Severity == DiagnosticSeverity.Error)).IsFalse();

        var generated = result.GeneratedSourceContaining("CustomerListView_VistaAccessors");
        await Assert.That(generated).IsEqualTo(SingleKeyGolden);
    }

    // ---- typed CRUD view: class YView : View<TQuery, TCrud>, partial ------------------------------

    private const string CrudViewSource = @"
namespace App
{
    public sealed class OrderRow
    {
        public int OrderId { get; set; }
        public decimal Total { get; set; }
    }

    public sealed class OrderCrud
    {
    }

    public partial class OrderView : a2n.Vista.Authoring.View<OrderRow, OrderCrud>
    {
    }
}
";

    [Test]
    public async Task CrudView_Emits_Accessor_Map_And_ModuleInitializer()
    {
        var result = GeneratorTestHarness.Run(CrudViewSource);

        await Assert.That(result.Diagnostics.Any(static d => d.Severity == DiagnosticSeverity.Error)).IsFalse();

        var generated = result.GeneratedSourceContaining("OrderView_VistaAccessors");

        // Accessors derive from TQuery (OrderRow), not TCrud — cast + property read, no reflection.
        await Assert.That(generated.Contains("file static class OrderView_VistaAccessors", StringComparison.Ordinal)).IsTrue();
        await Assert.That(generated.Contains("[\"OrderId\"] = static row => ((global::App.OrderRow)row).OrderId,", StringComparison.Ordinal)).IsTrue();
        await Assert.That(generated.Contains("[\"Total\"] = static row => ((global::App.OrderRow)row).Total,", StringComparison.Ordinal)).IsTrue();
        await Assert.That(generated.Contains("[global::System.Runtime.CompilerServices.ModuleInitializer]", StringComparison.Ordinal)).IsTrue();
        await Assert.That(generated.Contains("new global::App.OrderView().Name, Map);", StringComparison.Ordinal)).IsTrue();
    }

    // ---- non-partial view → VISTA0001, no accessor source -----------------------------------------

    private const string NonPartialViewSource = @"
namespace App
{
    public sealed class WidgetRow
    {
        public int Id { get; set; }
    }

    public class WidgetView : a2n.Vista.Authoring.View<WidgetRow>
    {
    }
}
";

    [Test]
    public async Task NonPartialView_Reports_VISTA0001_And_Emits_No_Accessor_Source()
    {
        var result = GeneratorTestHarness.Run(NonPartialViewSource);

        var vista0001 = result.Diagnostics
            .Where(static d => d.Id == "VISTA0001")
            .ToArray();

        await Assert.That(vista0001.Length).IsEqualTo(1);
        await Assert.That(vista0001[0].Severity).IsEqualTo(DiagnosticSeverity.Error);

        // No accessor source emitted for the skipped non-partial view.
        await Assert.That(result.HasGeneratedSourceContaining("WidgetView")).IsFalse();
    }

    // ---- incremental cache reuse on an unrelated edit (equatable model, R1.3) ---------------------

    // An unrelated edit appended to the view's syntax tree: a plain class with NO base list, so it is
    // not a generator candidate. It changes the tree text (forcing the semantic transform to re-run)
    // but leaves the CustomerListView declaration and its TQuery (CustomerListItem) shape identical, so
    // the equatable ViewModel compares equal and the downstream model stage is served from cache.
    private const string UnrelatedEdit = @"
namespace App
{
    public sealed class UnrelatedThing
    {
        public int Value { get; set; }
        public string Label { get; set; } = string.Empty;
    }
}
";

    [Test]
    public async Task UnrelatedEdit_Reuses_Cached_ViewModel_Step()
    {
        var result = GeneratorTestHarness.RunIncremental(SingleKeyViewSource, UnrelatedEdit);

        // The tagged equatable-model stage must be present in the tracked steps of the second run.
        var trackedSteps = result.Results.Single().TrackedSteps;
        await Assert.That(trackedSteps.ContainsKey(TrackingNames.ViewModel)).IsTrue();

        // On the unrelated edit, every output of the model stage must be served from cache: either
        // Cached (input node unchanged, not re-executed) or Unchanged (re-executed because the tree
        // text changed, but the equatable ViewModel compared equal so no new value flowed downstream).
        // It must NOT be New/Modified — that would mean the unrelated edit regenerated the view (R1.3).
        var outcomes = trackedSteps[TrackingNames.ViewModel]
            .SelectMany(static step => step.Outputs)
            .Select(static output => output.Reason)
            .ToArray();

        await Assert.That(outcomes.Length).IsGreaterThan(0);
        await Assert.That(outcomes.All(static reason =>
                reason is IncrementalStepRunReason.Cached or IncrementalStepRunReason.Unchanged))
            .IsTrue();
    }
}
