namespace a2n.Vista.Client.TypeScript.Pipeline;

/// <summary>
/// Where the generator reads the OpenAPI document from: a local file path or an HTTPS URL
/// (design §A.1/§A.2, Requirements 1.1, 1.3). A closed, discriminated set — the acquire stage
/// selects <c>FileSource</c> or <c>HttpsSource</c> by pattern-matching the case.
/// </summary>
public abstract record OpenApiSourceLocation
{
    private OpenApiSourceLocation() { }

    /// <summary>A local file path source (Requirement 1.1).</summary>
    /// <param name="Path">The local path to the OpenAPI document.</param>
    public sealed record File(string Path) : OpenApiSourceLocation;

    /// <summary>An HTTPS URL source (Requirement 1.3). Only the <c>https</c> scheme is accepted.</summary>
    /// <param name="Url">The absolute HTTPS URL of the OpenAPI document.</param>
    public sealed record Https(Uri Url) : OpenApiSourceLocation;
}

/// <summary>
/// The configuration that drives a single generator run (design §A.1). Supplied from the command
/// line by <c>CommandLine</c>/<c>Program</c> and consumed unchanged by the buffered pipeline.
/// </summary>
/// <param name="Source">The document source location (file or HTTPS URL).</param>
/// <param name="OutputDirectory">The directory the generated TypeScript is written into.</param>
/// <param name="EmitWriteFacets">
/// Whether create/update/delete facets are emitted. Defaults to <c>false</c>: the read surface is
/// generated by default and the write surface is an explicit opt-in (Requirements 5.1, 10.2).
/// </param>
/// <param name="DefaultBaseUrl">
/// An optional base URL baked into the generated client's default constructor argument. When
/// absent, the consumer supplies the base URL at construction.
/// </param>
/// <param name="DefaultTransportHint">
/// Reserved for future transport selection; the <c>fetch</c>-backed default transport is emitted
/// regardless of this value.
/// </param>
public sealed record GenerationConfig(
    OpenApiSourceLocation Source,
    string OutputDirectory,
    bool EmitWriteFacets = false,
    string? DefaultBaseUrl = null,
    string? DefaultTransportHint = null);
